### ISSUE TITLE
Per Page Feature?

### ISSUE THREAD

**Issue by SanjayBanjade** [triniwiz/nativescript-pager#100]
Hello! Thanks for building this great component.

Is there any way to specify per page property? You know like show 3 or 4 per slide. Currently, I can only do 1 per slide. I tried the following:
````
<Pager @selectedIndexChange="$emit('change')" spacing="2%" peaking="10%">
    <PagerItem v-for="(item, index) in [0,1,2,3,4,5,6,7,8,9]" :key="index"> 
        <Label height="65" width="65" background="#cbcbcb" class="img-rounded-circle"></Label>
    </PagerItem>
</Pager>
````

Still shows 1 per page. Please help!

It would be great if  I could specify `perPage` as a prop. Just took idea from [Swiper](https://github.com/surmon-china/vue-awesome-swiper) Component.

**Comment by triniwiz** [comment]
Very interesting feature @SanjayBanjade I'll look into it

**Comment by SanjayBanjade** [comment]
@triniwiz And is there something like auto paging? You know like switching automatically to next slide after few seconds?

**Comment by triniwiz** [comment]
No but all good suggestions

**Comment by triniwiz** [comment]
@SanjayBanjade u can open a new issue to track the other feature , now u can use `perPage="2"` or any number of your choice

**Comment by SanjayBanjade** [comment]
Oh my! Thanks @triniwiz! That was super fast. And yeah let me create the issue right away.
