### ISSUE TITLE
Auto slide after certain interval

### ISSUE THREAD

**Issue by sanjade** [triniwiz/nativescript-pager#101]
It would be great if there's something like auto slide which basically changes the slides after user-defined intervals. We could use the following props:

```
autoplay: Boolean
autoplayDelay: Number
```
Thanks!

**Comment by s3477631** [comment]
you can quite easily achieve this by binding the selectIndex property to a variable that is then manipulated using a setInterval method. The method can be triggered a variety of ways. 

in methods: 

      animateMetho(){
         setInterval(() => {
         if(this.animatepage == 3){ 
          this.animatepage = 0 .  // resets the slide to the beginning
        }
        else {
          this.animatepage++
        }
      }, 2000);
      },

**Comment by shiv19** [comment]
this.animatepage = (this.animatepage + 1) % this.slides.length;
