### ISSUE TITLE
Pager does not refresh/scale layout on *device* orientation change

### ISSUE THREAD

**Issue by MCurran16** [triniwiz/nativescript-pager#102]
### Which platform(s) does your issue occur on?
- Both 
- Android: **8.1.0**, iOS: **12.1**
- Emulator & devices

### Please, provide the following version numbers that your issue occurs with:

- CLI: 5.1.0
- Cross-platform modules: 5.2.2
- Runtime(s): 5.1.0

### Please, tell us how to recreate the issue in as much detail as possible. 

When I have a Pager in portrait orientation, everything looks fine and it fills the width of the view. When I change the orientation to landscape, it is the same width as it was in portrait orientation.

I have tried to call `refresh()` after a couple seconds as a hacky work-around, but that did not work. 

Thanks!

**Comment by romandragan** [comment]
+1

**Comment by joralegre** [comment]
Hack:
After rotation:

page.getViewById("pager").width="99%";
page.getViewById("pager").heigth="99%";

Then setimeout 350ms
page.getViewById("pager").width="100%";
page.getViewById("pager").heigth="100%";
 page.getViewById("pager").refresh();


Hope it helps!
