### ISSUE TITLE
Pager failing to restore state after navigateBack

### ISSUE THREAD

**Issue by bbc91** [triniwiz/nativescript-pager#104]
Greetings.

I use Pager on my main App page and it works correctly. When I navigate to another page, and then navigate back everything is still ok, but when I navigate to another page, but also lock the device screen, and then unlock it, and then navigate back, the Pager crashes.

`System.err: com.tns.NativeScriptException:
System.err: Calling js method restoreState failed
System.err: Error: java.lang.IllegalStateException: Fragment no longer exists for key f0: index 3
System.err:     android.support.v4.app.FragmentManagerImpl.getFragment(FragmentManager.java:938)
System.err:     com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1120)
System.err:     com.tns.Runtime.callJSMethodImpl(Runtime.java:1000)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:987)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:967)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:959)
System.err:     com.tns.gen.android.support.v4.view.PagerAdapter_vendor_19696_24_PagerStateAdapter.restoreState(PagerAdapter_vendor_19696_24_PagerStateAdapter.java:110)
System.err:     android.support.v4.view.ViewPager.onRestoreInstanceState(ViewPager.java:1461)
System.err:     android.view.View.dispatchRestoreInstanceState(View.java:14769)
System.err:     android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3121)
System.err:     android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3127)
System.err:     android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3127)
System.err:     android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3127)
System.err:     android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3127)
System.err:     android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3127)
System.err:     android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3127)
System.err:     android.view.View.restoreHierarchyState(View.java:14747)
System.err:     com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1120)
System.err:     com.tns.Runtime.callJSMethodImpl(Runtime.java:1000)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:987)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:967)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:959)
System.err:     com.tns.FragmentClass.onCreateView(FragmentClass.java:45)
System.err:     android.support.v4.app.Fragment.performCreateView(Fragment.java:2439)
System.err:     android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
System.err:     android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
System.err:     android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
System.err:     android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
System.err:     android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
System.err:     android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
System.err:     android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
System.err:     android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
System.err:     android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
System.err:     android.os.Handler.handleCallback(Handler.java:743)
System.err:     android.os.Handler.dispatchMessage(Handler.java:95)
System.err:     android.os.Looper.loop(Looper.java:148)
System.err:     android.app.ActivityThread.main(ActivityThread.java:5425)
System.err:     java.lang.reflect.Method.invoke(Native Method)
System.err:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:772)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:662)
System.err: File: "file:///data/data/sellfer.pos/files/app/vendor.js, line: 19922, column: 40
System.err: StackTrace:
System.err:     Frame: function:'PagerStateAdapter.restoreState', file:'file:///data/data/sellfer.pos/files/app/vendor.js', line: 19922, column: 41
System.err:     Frame: function:'FragmentCallbacksImplementation.onCreateView', file:'file:///data/data/sellfer.pos/files/app/vendor.js', line: 61207, column: 32
System.err:     Frame: function:'FragmentClass.onCreateView', file:'file:///data/data/sellfer.pos/files/app/vendor.js', line: 58766, column: 34
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1120)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1000)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:987)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:967)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:959)
System.err:     at com.tns.gen.android.support.v4.view.PagerAdapter_vendor_19696_24_PagerStateAdapter.restoreState(PagerAdapter_vendor_19696_24_PagerStateAdapter.java:110)
System.err:     at android.support.v4.view.ViewPager.onRestoreInstanceState(ViewPager.java:1461)
System.err:     at android.view.View.dispatchRestoreInstanceState(View.java:14769)
System.err:     at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3121)
System.err:     at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3127)
System.err:     at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3127)
System.err:     at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3127)
System.err:     at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3127)
System.err:     at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3127)
System.err:     at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3127)
System.err:     at android.view.View.restoreHierarchyState(View.java:14747)
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1120)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1000)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:987)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:967)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:959)
System.err:     at com.tns.FragmentClass.onCreateView(FragmentClass.java:45)
System.err:     at android.support.v4.app.Fragment.performCreateView(Fragment.java:2439)
System.err:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
System.err:     at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
System.err:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
System.err:     at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
System.err:     at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
System.err:     at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
System.err:     at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
System.err:     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
System.err:     at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
System.err:     at android.os.Handler.handleCallback(Handler.java:743)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
System.err:     at android.os.Looper.loop(Looper.java:148)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:5425)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:772)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:662)
System.err: Caused by: java.lang.IllegalStateException: Fragment no longer exists for key f0: index 3
System.err:     at android.support.v4.app.FragmentManagerImpl.getFragment(FragmentManager.java:938)
System.err:     ... 41 more`

**Comment by felix-idf** [comment]
@bbc91 ,

I also had this issue, but only when I used tns-core-modules 5.1.x.
After upgrading tns-core-modules to 5.2.x (or now 5.3.1), I do not notice this issue anymore.
