### ISSUE TITLE
showNativePageIndicator not working in version 9.5.0

### ISSUE THREAD

**Issue by demetrio812** [triniwiz/nativescript-pager#113]
Hello,
I've test the latest Angular demo from the latest version, adding `showNativePageIndicator="true"` doesn't show anything, is something else required to show them?

I'm using the latest NS (5.3.2)

Thanks,
Dem

**Comment by triniwiz** [comment]
That was removed in v9

**Comment by demetrio812** [comment]
ah ok, I think you should update the doc as that's not clear, also I still see the reference about the property in the code, but yes I see it's not used anywhere, thanks for replying so fast

**Comment by triniwiz** [comment]
@demetrio812 I can add it back it's going to need some extra work on ios since the core class changed

**Comment by demetrio812** [comment]
@triniwiz I understand, right now I've implemented them in nativescript with StackLayout because I also needed the possibility of changing the images for the dots and the native one is a bit limited. Also I wanted to have a separate component so I could decide positioning.

I only think it's good to write in the documentation that it's not available in v9, so less time for you spent replying to questions like mine :)

**Comment by triniwiz** [comment]
you can use `showIndicator` with an indicator of your choice 😄
