### ISSUE TITLE
Incorrect reference to this

### ISSUE THREAD

**Issue by FranciZ** [triniwiz/nativescript-pager#114]
Using this repo as a learning resource for myself and stumbled into this while inspecting the code. Shouldn't this be `position` instead of `this.position`?

https://github.com/triniwiz/nativescript-pager/blob/172a493c13bf65c7f765a235751271888a1979be/src/pager.android.ts#L549

**Comment by triniwiz** [comment]
I believe that was removed if you are referring to https://github.com/triniwiz/nativescript-pager/commit/42f32718220a074d3ab2a0198bee77d9b2e2c277#diff-c51c9565c029ef043828949779812fc2L533

**Comment by FranciZ** [comment]
Nice, never mind then. A quick question about the Template here if you have a minute: https://github.com/triniwiz/nativescript-pager/blob/199e6bf0981bf3b52eb229d0494ff0f3d5e2fcc1/src/pager.common.ts#L82

When I try to reimplement this I can't seem to get the `string | Template` type from the `itemTemplate`. 

I get an error with the below XML:

```xml
<Page xmlns="http://schemas.nativescript.org/tns.xsd"
      loaded="pageLoaded" class="page"
      xmlns:ui="nativescript-simple-ui-plugin">
    <StackLayout class="p-20">
        <ui:SimpleUiPlugin items="{{items}}" id="myCardStackView">
            <ui:SimpleUiPlugin.itemTemplate>
                <template>
                    <GridLayout>
                        <Button text="HELLO"/>
                    </GridLayout>
                </template>
            </ui:SimpleUiPlugin.itemTemplate>
        </ui:SimpleUiPlugin>
    </StackLayout>
</Page>
```

I get this error:
```
Module 'ui/template' not found for element 'Template'.
System.err:    > com.tns.NativeScriptException: Failed to find module: "ui/template", relative to: app/tns_modules/
```

Do I need to implement the template class myself? I can't find it in this repo or in the [ListView](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/list-view/list-view-common.ts) which I'm also trying to learn from for this.

**Comment by triniwiz** [comment]
https://github.com/triniwiz/nativescript-pager/blob/master/src/pager.common.ts#L30-L32

**Comment by FranciZ** [comment]
I've added those to the common file but it does not help the issue. Still get the same error when adding a template element.
