### ISSUE TITLE
TypeError: Cannot read property 'verticalviewpager' of undefined tns run android --bundle

### ISSUE THREAD

**Issue by eadortsu** [triniwiz/nativescript-pager#115]
### Which platform(s) does your issue occur on?
- Android
- Android 8.0.0
- device.

### Please, provide the following version numbers that your issue occurs with:

- CLI: 5.3.2
- Cross-platform modules: "version": "5.3.1"

- Runtime(s): 
"tns-ios": {
      "version": "5.0.0"
    },
    "tns-android": {
      "version": "5.0.0"
    }

- Plugin(s): 
 "dependencies": {
    "@vue/devtools": "^5.0.6",
    "nativescript-pager": "^9.5.0",
    "nativescript-plugin-firebase": "^8.2.0",
    "nativescript-socketio": "^3.2.1",
    "nativescript-theme-core": "^1.0.4",
    "nativescript-toasty": "^1.3.0",
    "nativescript-vue": "^2.0.0",
    "nativescript-vue-devtools": "^1.2.0",
    "tns-core-modules": "^5.0.2",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0",
    "@babel/preset-env": "^7.0.0",
    "babel-loader": "^8.0.2",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "clean-webpack-plugin": "^0.1.19",
    "copy-webpack-plugin": "^4.5.2",
    "css-loader": "^1.0.0",
    "lazy": "1.0.11",
    "nativescript-dev-webpack": "next",
    "nativescript-vue-template-compiler": "^2.0.0",
    "nativescript-worker-loader": "~0.9.0",
    "node-sass": "^4.9.2",
    "sass-loader": "^7.1.0",
    "terser-webpack-plugin": "^1.1.0",
    "vue-loader": "^15.2.6",
    "webpack": "^4.16.4",
    "webpack-bundle-analyzer": "~2.13.1",
    "webpack-cli": "^3.1.0"
  }

### Please, tell us how to recreate the issue in as much detail as possible. 
Trying to create an Onboarding page in a nativescript-vue app.
it runs with no errors on ios but get the following error on `tns run android --bundle`

System.err: com.tns.NativeScriptException: 
System.err: Calling js method onCreateView failed
System.err: 
System.err: TypeError: Cannot read property 'verticalviewpager' of undefined
System.err: File: "file:///data/data/com.citizencop.user/files/app/vendor.js, line: 7682, column: 18
System.err: 
System.err: StackTrace: 
System.err:     Frame: function:'initPagerStateAdapter', file:'file:///data/data/com.citizencop.user/files/app/vendor.js', line: 7682, column: 19
System.err:     Frame: function:'Pager.createNativeView', file:'file:///data/data/com.citizencop.user/files/app/vendor.js', line: 7021, column: 5
System.err:     Frame: function:'ViewBase._setupUI', file:'file:///data/data/com.citizencop.user/files/app/vendor.js', line: 47407, column: 25
System.err:     Frame: function:'', file:'file:///data/data/com.citizencop.user/files/app/vendor.js', line: 47462, column: 13
System.err:     Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/com.citizencop.user/files/app/vendor.js', line: 58171, column: 20
System.err:     Frame: function:'ViewCommon.eachChild', file:'file:///data/data/com.citizencop.user/files/app/vendor.js', line: 48859, column: 10
System.err:     Frame: function:'ViewBase._setupUI', file:'file:///data/data/com.citizencop.user/files/app/vendor.js', line: 47461, column: 10
System.err:     Frame: function:'', file:'file:///data/data/com.citizencop.user/files/app/vendor.js', line: 47462, column: 13
System.err:     Frame: function:'ContentView.eachChildView', file:'file:///data/data/com.citizencop.user/files/app/vendor.js', line: 44710, column: 7
System.err:     Frame: function:'PageBase.eachChildView', file:'file:///data/data/com.citizencop.user/files/app/vendor.js', line: 59611, column: 36
System.err:     Frame: function:'ViewCommon.eachChild', file:'file:///data/data/com.citizencop.user/files/app/vendor.js', line: 48859, column: 10
System.err:     Frame: function:'ViewBase._setupUI', file:'file:///data/data/com.citizencop.user/files/app/vendor.js', line: 47461, column: 10
System.err:     Frame: function:'ViewBase._addViewCore', file:'file:///data/data/com.citizencop.user/files/app/vendor.js', line: 47332, column: 12
System.err:     Frame: function:'ViewBase._addView', file:'file:///data/data/com.citizencop.user/files/app/vendor.js', line: 47315, column: 10
System.err:     Frame: function:'FragmentCallbacksImplementation.onCreateView', file:'file:///data/data/com.citizencop.user/files/app/vendor.js', line: 54573, column: 13
System.err:     Frame: function:'FragmentClass.onCreateView', file:'file:///data/data/com.citizencop.user/files/app/vendor.js', line: 52139, column: 34
System.err: 
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1116)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:996)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:983)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:967)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:959)
System.err:     at com.tns.FragmentClass.onCreateView(FragmentClass.java:45)
System.err:     at android.support.v4.app.Fragment.performCreateView(Fragment.java:2439)
System.err:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
System.err:     at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
System.err:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
System.err:     at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
System.err:     at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
System.err:     at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
System.err:     at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
System.err:     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
System.err:     at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
System.err:     at android.os.Handler.handleCallback(Handler.java:789)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:98)
System.err:     at android.os.Looper.loop(Looper.java:164)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6695)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:772)

### Is there any code involved? 
 <template>
    <Page actionBarHidden="true" backgroundSpanUnderStatusBar="false">
        <GridLayout rows="*, auto, auto" columns="*, *">

            <Pager row="0" colSpan="2" width="100%" height="100%" horizontalAlignment="center" verticalAlignment="center" for="item in items" v-model="pagerIndex">
                <v-template>
                    <GridLayout class="pager-item" height="100%" rows="auto, *" columns="*" width="100%" verticalAlignment="center">
                        <Img row="0" :src="item.image" height="80%" width="70%" class="m-t-30" verticalAlignment="center"></Img>
                        <Label row="1" class="pager-text m-y-10" :text="item.text" textWrap="true" verticalAlignment="bottom"></Label>
                    </GridLayout>
                </v-template>
            </Pager>

            <StackLayout row="1" colSpan="2" orientation="horizontal" class="m-b-30" horizontalAlignment="center" verticalAlignment="bottom">
                <Label class="pager-indicator" v-bind:class="{ 'pager-indicator-active' : index === pagerIndex }" v-for="(item, index) in items"></Label>
            </StackLayout>

            <Button row="2" col="0" text="Skip To Login" class="btn btn-secondary" @tap="$navigateTo(loginPage)"></Button>
            <Button row="2" col="1" :text="pagerIndex === items.length - 1 ? 'Login': 'Next'" class="btn btn-primary" @tap="pagerIndex === items.length - 1 ? $navigateTo(loginPage) : pagerIndex = pagerIndex + 1"></Button>

        </GridLayout>
    </Page>
</template>

<script lang="ts">

   // import { setScreenName } from "";
    import LoginPage from "./Login.vue"

    export default {
        components: {},
        created() {
            //setScreenName("onboarding");
        },
        data() {
            return {
                loginPage: LoginPage,
                pagerIndex: 0,
                items: [
                    {
                        image: "~/assets/images/onboarding/onboarding01.png",
                        text: "Maak nu je eigen FPR spelerskaart"
                    },
                    {
                        image: "~/assets/images/onboarding/onboarding02.png",
                        text: "Test je skills"
                    },
                    {
                        image: "~/assets/images/onboarding/onboarding03.png",
                        text: "Houd ze bij en check je vooruitgang"
                    }
                ]
            };
        }
    };
</script>

**Comment by triniwiz** [comment]
If it’s an upgrade you can try nuking the next project

**Comment by eadortsu** [comment]
> If it’s an upgrade you can try nuking the next project
Please your comment is unclear

**Comment by triniwiz** [comment]
If you upgraded the this project using non then try deleting node_modules, package-lock.json and platforms

**Comment by eadortsu** [comment]
> If you upgraded the this project using non then try deleting node_modules, package-lock.json and platforms

Thank, i have fixed it now.

**Comment by tahir-jamil** [comment]
Hi @triniwiz  i try to setup pager in playground but issue is reproduced (TypeError: Cannot read property 'verticalviewpager' of undefined )

hear is the link for project
https://play.nativescript.org/?template=play-ng&id=GdeuPM&v=2

can you please test it
