### ISSUE TITLE
iOS SafeArea margin

### ISSUE THREAD

**Issue by pboulch** [triniwiz/nativescript-pager#119]
### Which platform(s) does your issue occur on?
- iOS - iPhone X

### Please, provide the following version numbers that your issue occurs with:

- CLI: 5.2.3
- Cross-platform modules: 5.3.1
- Runtime(s): 5.2.1 (Android) & 5.3.1 (iOS) 
- Plugin(s): 9.5.0

### Please, tell us how to recreate the issue in as much detail as possible. 
With iPhone X, I have a pager that takes all the space of the screen, and I would like it to cover the safe area of the top of the screen but I get a margin that I can not delete. It worked with versions before 9.x

![image](https://user-images.githubusercontent.com/40267808/58559144-bd6c4880-8222-11e9-8ed5-6d0ba3e12073.png)

### Code
```
<Pager [items]="offersList" #pager [selectedIndex]="currentPagerIndex" (selectedIndexChange)="onIndexChanged($event)"
    class="pager" style="background-color: green; padding-top: 0; margin-top: 0;" iosOverflowSafeArea="true">
    <ng-template let-i="index" let-item="item" style="background-color: blue; margin-top: 0;">
        <StackLayout style="width: 100%; background-color: darkorange; margin-top: 0; " iosOverflowSafeArea="true">
        </StackLayout>
    </ng-template>
</Pager>
```

**Comment by triniwiz** [comment]
update to the latest version

**Comment by pboulch** [comment]
Hi, 
Same problem with NS7 & @nativescript-community/ui-pager : 
```
"@nativescript/core": "~7.0.0"
 "@nativescript-community/ui-pager": "^13.0.0-alpha.10",
```
![image](https://user-images.githubusercontent.com/40267808/95876859-ce641e00-0d73-11eb-8768-d86d7a6af5a2.png)

```
<Pager
  backgroundColor="orange"
  row="1"
  #pager
  [selectedIndex]="1"
>
  <StackLayout *pagerItem backgroundColor="red" ios:iosOverflowSafeArea="true">
    <label text="First"></label>
  </StackLayout>
  <StackLayout *pagerItem backgroundColor="white">
    <label text="Second"></label>
  </StackLayout>
  <StackLayout *pagerItem backgroundColor="black">
    <label text="Third" color="white"></label>
  </StackLayout>
  <StackLayout *pagerItem backgroundColor="green">
    <label text="Fourth"></label>
  </StackLayout>
</Pager>
```
