### ISSUE TITLE
Dynamic construction of the pager content

### ISSUE THREAD

**Issue by arnauvp** [triniwiz/nativescript-pager#12]
Thanks for the good work so far! This plugin is exactly what I need for a new app we're building.
I have been playing with the plugin for a couple of days but I can't manage to add the content dynamically with angular. Trying to use *ngFor results in an exception like:
```
JS:     com.tns.gen.android.support.v4.view.PagerAdapter_frnal_ts_helpers_l58_c38__PagerAdapter.instantiateItem(android.support.v4.view.PagerAdapter.java)
JS:     android.support.v4.view.ViewPager.addNewItem(ViewPager.java:1034)
...
JS: Caused by: java.lang.IllegalArgumentException: Cannot add a null child view to a ViewGroup
JS:     android.view.ViewGroup.addView(ViewGroup.java:4189)
JS:     android.view.ViewGroup.addView(ViewGroup.java:4171)
```
I also tried creating the Nativescript views with code and pushing them to the items array: 
`this.pager.nativeElement.items.push(someStackLayoutWithChildren);`

In the end the problem seems to be the _nativeView property being `undefined` in `instantiateItem`.
Could you guys provide some guidance on how this could be achieved? I'm using the android emulator.

Thanks in advance!

**Comment by triniwiz** [comment]
@arnauvp you can upgrade to `2.3.0` that should fix your problem

**Comment by arnauvp** [comment]
So fast!!! That allows me to programmatically inject Nativescript components in the slider, big win! I am still trying to figure out how to render full angular components in there, since *ngFor still complains (I guess since <template> nodes don't map to a real Android View). I'll retry a few of the things I had previously attempted with ComponentFactoryResolver and Renderer. I'll keep you posted!

**Comment by arnauvp** [comment]
This image summarizes how I got it working. There's probably a better way...
[slide-page] is just a directive to get hold of the placeholder stacklayout using ViewContainerRef and @ViewChild (should be called something else now that I only need one of these in the page).
Then I create a component in the placeholder, remove it with [ViewUtil](https://github.com/NativeScript/nativescript-angular/blob/master/nativescript-angular/view-util.ts) and add it to the slidder after wrapping it with a new StackLayout.

![slider_placeholder_working](https://cloud.githubusercontent.com/assets/1090103/23213181/3d1a9072-f90a-11e6-890b-40a62dfa7770.png)

**Comment by hauthorn** [comment]
@arnauvp Do you have a full code example? I could use some inspiration and guidance to achieve the same in my project.
