### ISSUE TITLE
pager UI issue

### ISSUE THREAD

**Issue by Vinaykummar** [triniwiz/nativescript-pager#128]
hi can you please update the carousel so that it looks same as the link below
https://github.com/jpapillon/react-native-carousel-pager

**Comment by triniwiz** [comment]
The pager has the peaking feature

**Comment by Vinaykummar** [comment]
How to use peaking feature in nativescript Angular .

**Comment by triniwiz** [comment]
set `peaking="5%"` `spacing="5%"` set those values to whatever u like `%, px, dip or a number`
