### ISSUE TITLE
(iOS) Page content does not use css-classes

### ISSUE THREAD

**Issue by ddfreiling** [triniwiz/nativescript-pager#13]
It seems to me when using nativescript-pager with Angular, that when I apply css classes to Pager content Layouts, they fail to apply. Haven't tested with just NS.

```
<Pager>
  <StackLayout class="m-20 bg-primary my-page">
    <Label text="Test"></Label>
  </StackLayout>
</Pager>
```
^ classes are not respected and content is completely plain.

This leads to having to use a lot of style="" attributes, which is annoying.

@triniwiz any idea why this might be?

**Comment by triniwiz** [comment]
With a couple changes introduced in v3 this now works as it would check the readme for the view changes

**Comment by ddfreiling** [comment]
Awesome, thanks a lot!
