### ISSUE TITLE
Pager does not know when to stop the current index number

### ISSUE THREAD

**Issue by cherimo** [triniwiz/nativescript-pager#133]
Hey,

I am using the pager plugin within my Nativescript 6.0.2 iOS project(Angular).
I have troubles when I scroll to much to left or to the right the current index goes -1.. -2.
And when you slide back its stuck at slide index 0 you have to slide back to index 0 to slide forward again. It seems that the plugin does not know when to stop the current index number.

I am using the exact sample of the demo folder with template selector.

Is there a way how to fix this?

**Comment by cherimo** [comment]
I tested it on multiple devices and different styles on iOS, the Horizontal Carousel doesn't work properly when you slide to much at the start or to much at the end.The index counter goes negative or goes above the array limit.

Where can I find the source for the iOs?

**Comment by mikkeldamm** [comment]
@cherimo i had the same issue. Solved it (a bit hacky) by listening for the index change event and setting the index by the min and max range.

```
<Pager #pager (selectedIndexChange)="onChange($event)">
```

```
@ViewChild(PagerComponent, { static: false }) pager: PagerComponent;

public items = [];

public onChange(e: { value: number; }) {
    const currentPagerIndex = e.value <= 0 ? 0 : e.value >= this.items.length ? this.items.length : e.value;
    setTimeout(() => {
        this.pager.selectedIndex = currentPagerIndex;
    }, 10);
}
```

**Comment by triniwiz** [comment]
@mikkeldamm actually that is the fix it needs to be done around [here](https://github.com/triniwiz/nativescript-pager/blob/master/src/pager.ios.ts#L903)

**Comment by romandragan** [comment]
Same for me.

**Comment by cherimo** [comment]
@triniwiz @mikkeldamm  Thx it works like a charm now :)
