### ISSUE TITLE
Spacing and Peaking for Vue

### ISSUE THREAD

**Issue by vzapo** [triniwiz/nativescript-pager#134]
Nativescript version : 6.0.0
Nativescript-pager: latest -> 11.0.9
Platform: Android

Hello,

I was looking at this and the Vue implementation for peaking and spacing attributes is missing. 
Tried to implementing like: 

```
<Pager height="100%" for="item in gallery" @selectedIndexChange="selectedIndexChange" spacing="2%" peaking="10%">
 <v-template>
   <GridLayout class="gallery-item" rows="*" columns="*">
	<Image stretch="fill" class="gallery-image" row="0" :src="item.image"/>
   </GridLayout>
  </v-template>
</Pager>
```
and the image is still displaying the only one. 
The code does not show any implementation into it https://github.com/triniwiz/nativescript-pager/blob/master/src/vue/pager.js or am i missing something?

Thank you.

**Comment by vzapo** [comment]
Hi,

Not sure but looks that basically this plugin development for Vue is dead?

**Comment by rigor789** [comment]
https://github.com/triniwiz/nativescript-pager/blob/02598865540e3ade7e55573d7b3d6870bc2f989e/src/vue/pager.js#L30

This passes all attributes down to the element (anything that's not a prop). 

So in theory - it should work, unless it doesn't work in other flavors either.

**Comment by vzapo** [comment]
> https://github.com/triniwiz/nativescript-pager/blob/02598865540e3ade7e55573d7b3d6870bc2f989e/src/vue/pager.js#L30
> 
> This passes all attributes down to the element (anything that's not a prop).
> 
> So in theory - it should work, unless it doesn't work in other flavors either.

This should do it. Thanks.
