### ISSUE TITLE
Pager automatically changes page after textfield focus\blur 

### ISSUE THREAD

**Issue by abinpey** [triniwiz/nativescript-pager#136]
Hello! I found a bug, ns-pager automatically changes page after textfield focus and blur event. Can you help me? Attached screen recording.

Versions:
- nativescript-pager: 11.0.9,
- nativescript-vue: 2.4.0,
- tns-android: 6.1.0-2019-08-13-154901-03
- tns-core-modules: 6.0.6

Thank you!

![nspagerissue](https://user-images.githubusercontent.com/25432233/63471568-31139f80-c478-11e9-9f71-5c1a39df80e8.gif)

**Comment by triniwiz** [comment]
First thing you want to ensure ita backed back by an observable array if using the dynamic feature

**Comment by triniwiz** [comment]
try updating to the latest version while using `ObservableArray`
