### ISSUE TITLE
page.getViewById(<id>) returns undefined for view within pager since nativescript-pager 11.x

### ISSUE THREAD

**Issue by felix-idf** [triniwiz/nativescript-pager#137]
### Which platform(s) does your issue occur on?
- only tested on Android
- Android version does not matter

### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.0.3
- Cross-platform modules: 6.0.6
- Runtime(s): tns-android 6.0.2, tns-ios 6.0.2
- Plugin(s): nativescript-pager 11.0.9

### Please, tell us how to recreate the issue in as much detail as possible. 
Open the sample app provided below and tap the button, you will see a log in the console. This actually should be the id of the ScrollView within the pager, but unfortunately it just returns 'undefined'.

This was working with NativeScript 5 and the latest 9.x.y version of the pager plugin.

### Is there any code involved? 
I have a pager component with just one page, that contains a ScrollView with a fixed id (just for this sample).

```
<pager:Pager items="{{items}}">
            <pager:Pager.itemTemplate>
                <GridLayout rows="*" columns="*">
                    <ScrollView row="0" id="myscrollview">
                        <StackLayout backgroundColor="yellow">
                            <Label text="{{ 'Chapter ' + number }}"/>
                        </StackLayout>
                    </ScrollView>
                </GridLayout>
            </pager:Pager.itemTemplate>
</pager:Pager>
```

Outside the pager, I have a button and on tap event of the button, I want to access the ScrollView of the current page using page.getViewById('myscrollview'). This returns undefined.

```
exports.test = function() {
    console.log(page.getViewById("myscrollview"));
};
```

I created 2 versions of the sample app with NS 5 + pager 9.x and NS 6 + pager 11.x.
[NS_6.zip](https://github.com/triniwiz/nativescript-pager/files/3530625/NS_6.zip)
[NS_5.zip](https://github.com/triniwiz/nativescript-pager/files/3530626/NS_5.zip)

Btw, this is just a simplified scenario for demonstrating this issue.
Usually we have a dynamic number of pages, that all contain a ScrollView and its id depends on the page-index. When I tap the button, I need to access the scrollview of the current page to get the current scroll positionfor bookmark etc.
I also tried to save the instance of the current ScrollView in the loaded-event of the ScrollView, but the problem is, that this event is called for multiple ScrollViews at once, so I would not be able to access the correct ScrollView instance this way.

**Comment by felix-idf** [comment]
The issue is not reproducable using v.10.0.0 of the plugin, so it is not related to NS 6.

**Comment by triniwiz** [comment]
Ok anyway to test on iOS? So v11 uses a new class on android so I'll look into when I get a chance

**Comment by felix-idf** [comment]
@triniwiz thanks for your feedback.

I just tested this behaviour on iOS 12 and iOS 10 and the issue did not occur there. I was able access the ScrollView vis page.getViewById('...') as expected.

**Comment by romandragan** [comment]
Same for me: it works on iOS but doesn't on Android.

**Comment by BMwanza** [comment]
Currently experiencing this on iOS 14.5 using `"@triniwiz/nativescript-pager": "^13.0.1"` Using {N} 8
