### ISSUE TITLE
strange effect when switching to fullscreen mode in Android app using pager v 11

### ISSUE THREAD

**Issue by felixkrautschuk** [triniwiz/nativescript-pager#138]
### Which platform(s) does your issue occur on?
- Android
- tested on multiple versions from 5 to 9
- device (tested on Google Pixel 3a and Nexus 4)

### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.0.3
- Cross-platform modules: 6.0.7
- Runtime(s): tns-android and tns-ios 6.0.2
- Plugin(s): nativescript-pager 11.0.9

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.

In our real app on Android, we provide a way to switch to a fullscreen mode for reading like some community members described it here:
https://rynop.com/2019/01/22/go-fullscreen-on-android-in-nativescript-angular/

This was working until NS 5 + pager v.9.5.0 (or even NS 6 + pager v.10.0.0) but on v. 11.0.9, we see a strange effect: the bottom part of the page gets overlapped by some kind of bar or strip.
Here you can compare the result using v.10 and v. 11 of the pager plugin:

v10:
![v10](https://user-images.githubusercontent.com/6443021/63604148-6086f100-c5cb-11e9-8920-616a0ae91d94.gif)

v11:
![v11](https://user-images.githubusercontent.com/6443021/63604273-9d52e800-c5cb-11e9-8ea5-65d78f9927f7.gif)

This is what we do:
```
function toggleAndroidFullScreenMode(fullscreen) {
    var View = android.view.View;
    if(platform.isAndroid && app.android.startActivity) {
        if(fullscreen) {
            app.android.startActivity.getWindow().getDecorView().setSystemUiVisibility(
                View.SYSTEM_UI_FLAG_LAYOUT_STABLE
                | View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
                | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
                | View.SYSTEM_UI_FLAG_HIDE_NAVIGATION // hide nav bar
                | View.SYSTEM_UI_FLAG_FULLSCREEN // hide status bar
                | (android.os.Build.VERSION.SDK_INT >= 19 ? View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY : null)
            );
        } else {
            app.android.startActivity.getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LAYOUT_STABLE);
        }
    }
}
```

On our test devices, this effect always looks the same, which means you see this blue stripe (= backgroundColor of the page) on the bottom only for a short time, so actually it is not a big problem. But some users of our real app say that this stripe won't disappear anymore until leaving the page that contains the pager component.
And this was not happening at all using pager 9.5.0 and 10.0.0, so I decided to report this issue here, even it might be a special use case concerning the fullscreen mode.

### Is there any code involved? 
The full sample project:
[NSPagerIssueFullscreen.zip](https://github.com/triniwiz/nativescript-pager/files/3535176/NSPagerIssueFullscreen.zip)

**Comment by triniwiz** [comment]
Can you test again after updating

**Comment by felix-idf** [comment]
@triniwiz unfortunately, the issue still exists using version 11.0.10 of the pager plugin.

**Comment by felixkrautschuk** [comment]
@triniwiz unfortunately this issue still persists using the latest configuration:
- NativeScript 6.4 (tns-android 6.4.1, tns-ios 6.4.2, @nativescript/core 6.4.1)
- nativescript-pager 12.0.0-alpha.6

I updated the sample app to the latest dependencies, you can grab it here:
[NSPagerIssueAndroidFullscreen.zip](https://github.com/triniwiz/nativescript-pager/files/4257282/NSPagerIssueAndroidFullscreen.zip)


I reviewed the whole scenario of toggling the fullscreen mode again on Android and iOS and Imade the following observations:
- When showing/hiding only the ActionBar without any other Android-specific code (see the `toggleAndroidFullScreenMode` method from my initial post in this thread), you can see kind of a bar/strip at the bottom of the screen on **ALL** devices and emulators on Android and iOS. 
As you can see in the GIFs, this issue does not occur on a normal page without the Pager component.

Android 10 emulator:
![pager_fullscreen_issue_actionbar](https://user-images.githubusercontent.com/6443021/75360001-74cae400-58b5-11ea-8cbb-12d33bd152f3.gif)

iOS 13 Simulator:
![pager_fullscreen_issue_refresh_ios](https://user-images.githubusercontent.com/6443021/75360071-91671c00-58b5-11ea-8fc9-d5604137056c.gif)


- When calling `myPager.refresh()`, this large bar/strip at the bottom is not visible anymore on Android anymore.
Android 10 emulator:
![pager_fullscreen_issue_refresh](https://user-images.githubusercontent.com/6443021/75369445-ba8ea900-58c3-11ea-9a15-c8cd20220184.gif)

But on iOS it has no effect. In addition, on pager elements that contain a huge amount of pages inside, this may cause performance issues on Android so it might not be the best idea.


- When also toggling the android-specific fullscreen mode using setSystemUiVisibility (see `toggleAndroidFullScreenMode` method in sample project), then there is a strange side effect on pages that contain a pager component: there is a small bar/strip at the bottom of the screen that has the same background color of the page (aqua blue in the sample app):

![IMG_20200226_183635](https://user-images.githubusercontent.com/6443021/75371507-29213600-58c7-11ea-8420-289f4a1dff61.jpg)


The only test device where we can reproduce it: Samsung Galaxy S4 mini.
Some of our beta-tester users notiticed that already using the Pager v.11.0.11 on the following devices:
- Samsung Galaxy S7 Android 8
- Samsung Galaxy J3 Android 8
.... not sure if it only ocurrs on Samsung devices, but even i that was the case, there are many users with those devices out there.


Can you have another look on this?
I know it is a very special use case and it is hard to reproduce on many devices, but it seems to be related to the Pager component in any way, as it does not occur on pages without Pager component.

**Comment by triniwiz** [comment]
I'll look at this with your demo but for now try calling `.requestLayout()`

**Comment by felixkrautschuk** [comment]
@triniwiz thanks for your help.
I already tried that while testing the latest pager version, but unfortunately calling requestLayout has no effect on Android und iOS

**Comment by triniwiz** [comment]
for android there is `._realizedItems`  a map with `<android.view.View, View>` you can try looping that an calling `requestLayout()` if that fails try setting the actual height on the pager between modes (full/regular) . Also after you change between modes do swiping to another page fix the layout issue ?

**Comment by felixkrautschuk** [comment]
@triniwiz thank you so much for your suggestions

```
page.actionBarHidden = true;

if(platform.isAndroid) {
    toggleAndroidFullScreenMode(true);

    setTimeout(() => {
            pager._realizedItems.forEach(function(view) {
                view.requestLayout();
            });
    }, 0);
}
```

Without the `setTimeout` call, this small bar at the bottom of the screen will still persist on the Samsung Galaxy S4 Mini (and probably on other devices from users who reported this issue on our real app).

But wrapping this into a `setTimeout` call will finally remove that ugly bar on the bottom... even with a timeout-value of 0 😀

By the way, this issue has nothing to do with the fullscreen functionality, as this will also occur on older Android devices when you start some text-selection within the HtmlView and then confirm/cancel it like this:

![pager_issue_android_textselection](https://user-images.githubusercontent.com/6443021/75564879-4122c200-5a4d-11ea-91a7-811ab13a3137.gif)
(Android 5 Emulator)

At the end, I tap on the HtmlView instance and in this event, I call code snipped from above to remove that bar again.

------------------------------

Is there anything similar we can do on iOS?
After hiding the ActionBar, there is a similar bar/strip at the bottom of the screen, as I already mentioned in one of the previous posts here.

I already tried `requestLayout` on pager, pager.parent, the htmlview within the current page of the pager,... but nothin helped.

Just in case you want to have a look, here is the latest version of the demo app:
[NSPagerIssueAndroidFullscreen.zip](https://github.com/triniwiz/nativescript-pager/files/4268060/NSPagerIssueAndroidFullscreen.zip)

**Comment by triniwiz** [comment]
you can try putting `iosOverflowSafeArea="true"` on the rootview and the pager

**Comment by felixkrautschuk** [comment]
@triniwiz I tried that but with no success.

This effect also occurs on iPhone 6 (as an example) so it is not caused by the ios safe area

**Comment by felixkrautschuk** [comment]
@triniwiz in our real app, enabling the fullscreen on iOS works as expected using pager 12.0.0.alpha8.

When using a Label instead of the HtmlView component within the demo app, the fullscreen works as expected on iOS, so it seems to be related to the HtmlView.
We use a modified HtmlView in our app and something there seems to fix this issue for us.

Thanks again for your help, suggestions and investigations on this.
