### ISSUE TITLE
NS 6.1 - IOS crashes on pager invocation

### ISSUE THREAD

**Issue by jawa-the-hutt** [triniwiz/nativescript-pager#139]
### Which platform(s) does your issue occur on?
- iOS only
- iOS 12
- What type of device?:  **Emulator** and an **iPhone XS Max**

### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.1.0
- Cross-platform modules: 6.1.0
- Plugin(s): using the vue demo and the vanilla NS demo.  here's a copy of the relevant package.json for Vue:
```
"nativescript": {
    "id": "org.nativescript.application",
    "tns-ios": {
      "version": "6.1.0"
    },
    "tns-android": {
      "version": "6.1.0"
    }
  },
  "dependencies": {
    "nativescript-pager": "file:../src",
    "nativescript-theme-core": "^2.0.17",
    "nativescript-vue": "2.4.0",
    "tns-core-modules": "6.1.0"
  },
  "devDependencies": {
    "@babel/core": "^7.5.5",
    "@babel/preset-env": "^7.5.5",
    "babel-loader": "^8.0.6",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "lazy": "1.0.11",
    "nativescript-dev-webpack": "1.2.0",
    "nativescript-vue-template-compiler": "^2.4.0",
    "node-sass": "^4.12.0",
    "terser-webpack-plugin": "^1.3.0",
    "typescript": "~3.5.3",
    "vue-loader": "^15.7.1"
  }
```

### Please, tell us how to recreate the issue in as much detail as possible. 
I'm primarily using the vue demo included in the repository.  All I've done is upgrade NS to 6.1 and NS-Vue to 2.4.0.  If you do this, then the pager will not load and will crash the app.  However, the vanilla NS demo will also produce the same error if you upgrade relevant packages to NS 6.1.0.

Here's the relevant error message in the console:
```
JavaScript error:
file:///app/webpack:/Users/garygambill/Code/OSS Projects/nativescript-pager/src/pager.ts:523:155: JS ERROR TypeError: undefined is not an object (evaluating 'this.indicatorView.intrinsicContentSize.height')
```
When using the debugger, `intrinsicContentSize` is truly undefined.

**Comment by jawa-the-hutt** [comment]
Just some further testing.  Below is a package.json that represents the latest version of each package that will still work.  Notice that `tns-core-modules` is at 6.1.0, but that the `tns-ios` version is set at `6.0.2`.  As soon as you change `tns-ios` to `6.1.0`, the error occurs.

```
{
  "nativescript": {
    "id": "org.nativescript.application",
    "tns-ios": {
      "version": "6.0.2"
    },
    "tns-android": {
      "version": "6.0.0"
    }
  },
  "dependencies": {
    "nativescript-pager": "file:../src",
    "nativescript-theme-core": "^2.0.17",
    "nativescript-vue": "2.4.0",
    "tns-core-modules": "^6.1.0"
  },
  "devDependencies": {
    "@babel/core": "^7.5.5",
    "@babel/preset-env": "^7.5.5",
    "babel-loader": "^8.0.6",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "lazy": "1.0.11",
    "nativescript-dev-webpack": "1.2.0",
    "nativescript-vue-template-compiler": "^2.4.0",
    "node-sass": "^4.12.0",
    "terser-webpack-plugin": "^1.3.0",
    "typescript": "~3.5.3",
    "vue-loader": "^15.7.1"
  }
}

```

**Comment by ShyshkovOleg** [comment]
Still crashes on invocation.
"tns-ios": {
            "version": "6.3.0"
        }
"dependencies": {
        "@angular/animations": "8.0.0",
        "@angular/common": "8.0.0",
        "@angular/compiler": "8.0.0",
        "@angular/core": "8.0.0",
        "@angular/forms": "8.0.0",
        "@angular/http": "8.0.0-beta.10",
        "@angular/platform-browser": "8.0.0",
        "@angular/platform-browser-dynamic": "8.0.0",
        "@angular/router": "8.0.0",
        "@nstudio/nativescript-cardview": "^1.0.0",
        "@nstudio/nativescript-checkbox": "^1.0.0",
        "nativescript-angular": "8.0.2",
        "nativescript-bcryptjs": "^1.0.1",
        "nativescript-oauth2": "^2.1.1",
        "nativescript-pager": "^11.0.11",
        "nativescript-plugin-firebase": "^9.0.4",
        "nativescript-theme-core": "~1.0.4",
        "nativescript-ui-sidedrawer": "7.0.0",
        "reflect-metadata": "~0.1.12",
        "rxjs": "~6.3.0",
        "tns-core-modules": "^6.3.0-next-2020-01-16-124141-03",
        "zone.js": "0.9.1"
    },
    "devDependencies": {
        "@angular/compiler-cli": "8.0.0",
        "@nativescript/schematics": "~0.5.0",
        "@ngtools/webpack": "8.0.0",
        "codelyzer": "~4.5.0",
        "nativescript-dev-webpack": "^1.4.1",
        "node-sass": "4.12.0",
        "tslint": "~5.11.0",
        "typescript": "3.4.5"
    },
