### ISSUE TITLE
angular *ngFor not working

### ISSUE THREAD

**Issue by developper89** [triniwiz/nativescript-pager#14]
How do you add dynamic slides based on a data array with *ngFor ? 
![capture d ecran 2017-03-25 a 11 36 35](https://cloud.githubusercontent.com/assets/1890132/24321558/75e1e380-114f-11e7-87a1-f5ad78910a10.png)

**Comment by triniwiz** [comment]
@developper89 the next update will fix this

**Comment by triniwiz** [comment]
As of https://github.com/triniwiz/nativescript-pager/commit/3621d9ff676e26357792f13a83ba07d5d9cc9397 You will need to a `template`

```
<Pager [items]="items" #pager [selectedIndex]="currentPagerIndex" (selectedIndexChanged)="onIndexChanged($event)" class="pager">
        <template pagerItemTemplate let-i="index" let-item="item">
            <GridLayout class="pager-item" rows="auto, *" columns="*" backgroundColor="red">
                <Label  [text]="item.title"></Label>
                <Image row="1" [src]="item.image"></Image>
            </GridLayout>
        </template>
    </Pager>
```
