### ISSUE TITLE
Pager V11 will freeze when resuming app in Android 

### ISSUE THREAD

**Issue by liuy97** [triniwiz/nativescript-pager#140]
### Which platform(s) does your issue occur on?
- Android
- emulator or device. Pixel 2 API 28, Android 9

### Please, provide the following version numbers that your issue occurs with:

- CLI: (run `tns --version` to fetch it)
6.0.3
- Cross-platform modules: (check the 'version' attribute in the
{
  "nativescript": {
    "id": "org.nativescript.demo",
    "tns-android": {
      "version": "6.0.2"
    },
    "tns-ios": {
      "version": "6.0.2"
    }
  },
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "dependencies": {
    "@angular/animations": "~8.2.0",
    "@angular/common": "~8.2.0",
    "@angular/compiler": "~8.2.0",
    "@angular/core": "~8.2.0",
    "@angular/forms": "~8.2.0",
    "@angular/platform-browser": "~8.2.0",
    "@angular/platform-browser-dynamic": "~8.2.0",
    "@angular/router": "~8.2.0",
    "nativescript-angular": "~8.2.0",
    "nativescript-pager": "~11.0.10",
    "nativescript-theme-core": "~1.0.6",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.4.0",
    "tns-core-modules": "~6.0.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~8.2.0",
    "@ngtools/webpack": "~8.2.0",
    "nativescript-dev-webpack": "~1.1.0",
    "typescript": "~3.5.3"
  },
  "gitHead": "42f2a6a9c94eaf9c68d2a41e0daaa1a2544bc28f",
  "readme": "NativeScript Application"
}

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.

### Is there any code involved? 
 - provide a code example to recreate the problem 
tns create demo --ng

<ActionBar title="My App" class="action-bar">
</ActionBar>

install nativescript-pager@11, Import PagerModule into AppModule and Change items.component.html

```
<Pager backgroundColor="orange" row="1" #pager [selectedIndex]="1" height="100%">
    <StackLayout *pagerItem backgroundColor="red">
        <label text="First"></label>
    </StackLayout>
    <StackLayout *pagerItem backgroundColor="white">
        <label text="Second"></label>
    </StackLayout>
    <StackLayout *pagerItem backgroundColor="black">
        <label text="Third" color="white"></label>
    </StackLayout>
    <StackLayout *pagerItem backgroundColor="green">
        <label text="Fourth"></label>
    </StackLayout>
</Pager>
```
 - run "tns run android --bundle"
- press the right-most button, which showed all the currently running apps.
![demo](https://user-images.githubusercontent.com/2961144/65033020-95753200-d944-11e9-804c-54ec331df96e.png)
![demo error](https://user-images.githubusercontent.com/2961144/65033197-d40aec80-d944-11e9-9db9-4f945846bf36.png)

**Comment by VanderSP** [comment]
I can confirm this... it´s when using Static mode items, works ok with Item.template mode...

switch/minimize then resume... and when suspend then resume...

it can leads to pager lock, pages disappearing, and even placeholder crash

**Comment by triniwiz** [comment]
Two things can be done to help 1. On loaded check the pager adapter instance to ensure it is not set to the static pager and if it is do nothing 2. In the _addChildFromBuilder remove the view from the parent if it has one :) ... you can try either 1 or 2

**Comment by VanderSP** [comment]
the first approach i tried... it works for suspended... but for switch/minimize there´s no effect (i guess it´s another problem involved)
