### ISSUE TITLE
Pager no longer work on playground?

### ISSUE THREAD

**Issue by rynop** [triniwiz/nativescript-pager#145]
Does `nativescript-pager` no longer work on https://play.nativescript.org? I know it used to work (in `v8.0.2` [here](https://play.nativescript.org/?template=play-ng&id=oMFtUF&v=116))

Ported your simple [demo-ng/app/test](https://github.com/triniwiz/nativescript-pager/tree/master/demo-ng/app/test) in the playground [here](https://play.nativescript.org/?template=play-ng&id=HWzzO3) but I get low level errors.

I'm using the Angular version of your plugin and getting just `[object Object]` on the screen where I use `<Pager>`.  I was hoping to create a playground that reproduces the problem.

```
tns info
✔ Getting NativeScript components versions information...
⚠ Update available for component nativescript. Your current version is 6.1.0 and the latest available version is 6.1.2.
⚠ Update available for component tns-core-modules. Your current version is 6.1.1 and the latest available version is 6.1.2.
✔ Component tns-android has 6.1.2 version and is up to date.
✔ Component tns-ios has 6.1.1 version and is up to date.
```

**Comment by triniwiz** [comment]
No I added some 3rd party deps iOS has a higher chance of working if I can port the dependency

**Comment by rynop** [comment]
Ah ok no worries, I don't need it to work in playground so closing this issue. I'll open another issue to describe the `[object Object]` I'm seeing.
