### ISSUE TITLE
(iOS) Crash on navigating back

### ISSUE THREAD

**Issue by ddfreiling** [triniwiz/nativescript-pager#15]
When navigating to a new component and then returning back to a page with a Pager component on, the app crashes with this log:
```
src/ios/pager.js:79:29: JS ERROR TypeError: null is not an object (evaluating 'this._ios.view')
```

See demo branch here:
https://github.com/ddfreiling/nativescript-pager/commits/demo-ng-test

**Comment by b4rtt** [comment]
Same problem here

**Comment by triniwiz** [comment]
Fixed
