### ISSUE TITLE
Indicator is not shown with version 11.0.11, Nativescript 6.2, IOS 13

### ISSUE THREAD

**Issue by prestig73** [triniwiz/nativescript-pager#155]
<Pager row="1" #pager [selectedIndex]="currentPagerIndex" indicator="worm" showIndicator="true">
        <StackLayout *pagerItem orientation="vertical" class="guided-tour-content">
            <miira-label text="AAA" class="guided-tour-title frutiger-bold"></miira-label>
            <miira-label text="Loren" customStyle="padding-top: 12;" class="guided-tour-text frutiger-light"></miira-label>
            <miira-label text="BBB" customStyle="padding-top: 56;" class="guided-tour-title frutiger-bold"></miira-label>
            <miira-label text="Loren" customStyle="padding-top: 12;" class="guided-tour-text frutiger-light"></miira-label>
        </StackLayout>
        <StackLayout *pagerItem orientation="vertical" class="guided-tour-content">
            <miira-label text="E-Post" class="guided-tour-title frutiger-bold"></miira-label>
            <miira-label text="Loren" customStyle="padding-top: 12;" class="guided-tour-text frutiger-light"></miira-label>
            <miira-label text="E-Post" customStyle="padding-top: 56;" class="guided-tour-title frutiger-bold"></miira-label>
            <miira-label text="Loren" customStyle="padding-top: 12;" class="guided-tour-text frutiger-light"></miira-label>
        </StackLayout>
        <StackLayout *pagerItem orientation="vertical" class="guided-tour-content">
            <miira-label text="EEE" class="guided-tour-title frutiger-bold"></miira-label>
            <miira-label text="Loren" customStyle="padding-top: 12;" class="guided-tour-text frutiger-light"></miira-label>
            <miira-label text="FFF" customStyle="padding-top: 56;" class="guided-tour-title frutiger-bold"></miira-label>
            <miira-label text="Loren" customStyle="padding-top: 12;" class="guided-tour-text frutiger-light"></miira-label>
        </StackLayout>
    </Pager>

Error is JavaScript error:
file:///node_modules/nativescript-pager/pager.js:162:0: JS ERROR TypeError: this._indicatorView.removeFromSuperview is not a function. (In 'this._indicatorView.removeFromSuperview()', 'this._indicatorView.removeFromSuperview' is undefined)

Can you fix it asap thank you?

**Comment by alex-lucid** [comment]
Can confirm this issue with latest NS (6.2) though iOS is 10.

`JS ERROR TypeError: undefined is not an object (evaluating 'this.indicatorView.intrinsicContentSize.height')`

**Comment by wuilmerj24** [comment]
Hi. I also have that problem. I tested it on ios 13 with NS 6.2.2

**Comment by alex-lucid** [comment]
Disabling indicator fixes an issue, but we need it...

**Comment by wuilmerj24** [comment]
@alex-lucid How to disable the indicator?

**Comment by alex-lucid** [comment]
> @alex-lucid How to disable the indicator?

Just do not use that property, showIndicator, and it will be Off by default

**Comment by triniwiz** [comment]
I'll see what I can do to address that it should be an issue around with swift version

**Comment by wuilmerj24** [comment]
@triniwiz Hi. It still has this problem in v12.0.0-alpha.8. ios v12.4
