### ISSUE TITLE
feature: Support for multple item templates

### ISSUE THREAD

**Issue by teren3ce** [triniwiz/nativescript-pager#16]
Hello triniwiz. nice work with the pager, please can there be support for multiple item template as it is with a listview [here](http://docs.nativescript.org/angular/ui/list-view#using-multiple-item-templates)

**Comment by lambourn** [comment]
The itemTemplate property either accepts a XML template or a function. This function acts as a factory to create new views (more specific: the function's interface should be [Template](https://docs.nativescript.org/api-reference/interfaces/_ui_core_view_.template.html))

**Comment by triniwiz** [comment]
Added in v7
