### ISSUE TITLE
Subviews tap event is not working in IOS

### ISSUE THREAD

**Issue by SandipFichadiya** [triniwiz/nativescript-pager#18]
Hello, we have implemented this plugin  in our ios application. we are not getting tap event of label or listview or image  . it  is working only for button . We have attached the demo code, can some one please help us in order to get this working?
we have implemented tap event for label in attached demo project as follows:

test.component.html
```
<Pager [items]="items | async" #pager [selectedIndex]="currentPagerIndex" readOnly="false" (selectedIndexChanged)="onIndexChanged($event)"
        class="pager">
        <template pagerItemTemplate let-i="index" let-item="item">
            <GridLayout class="pager-item" rows="auto, *" columns="*" backgroundColor="red">
                <Label [text]="item.title" (tap)="itemTapped()"></Label>
                <!--<Button [text]="item.title" (tap) = "itemTapped()"></Button>-->
                <Image stretch="fill" row="1" [src]="item.image"></Image>
            </GridLayout>
        </template>
    </Pager>
```

test.component.ts 
```

itemTapped(){
        console.log("itemTapped");
    }
```

[demo-ng.zip](https://github.com/triniwiz/nativescript-pager/files/965971/demo-ng.zip)

**Comment by RyeGuy12** [comment]
I am having the same issue. Let me know if you have found a solution

**Comment by triniwiz** [comment]
@RyeGuy12 this component is used in production and i've not come across this issue

**Comment by triniwiz** [comment]
should be working in the latest release
