### ISSUE TITLE
Angular 10 @nativescript-community/ui-pager 13.0.0-alpha.5 module import is not working

### ISSUE THREAD

**Issue by limux82** [triniwiz/nativescript-pager#183]
I have tried the version of @nativescript-community/ui-pager 13.0.0-alpha.5
I have problem in import the PagerModule from @nativescript-community/ui-pager/angular. I think the package is not compiled correctly. Checking in node-modules @nativescript-community/ui-pager/angular folder contains only the package.json file. The angular module is not exported

ERROR in src/app/shared/shared.module.ts:33:29 - error TS2307: Cannot find module '@nativescript-community/ui-pager/angular' or its corresponding type declarations.

33 import { PagerModule } from '@nativescript-community/ui-pager/angular';

**Comment by heerenjasper** [comment]
Also having this issue.

**Comment by triniwiz** [comment]
please use `@triniwiz/nativescript-pager` Thanks
