### ISSUE TITLE
Error: Can't resolve '@nativescript/core/data/observable-array/observable-array' Nativescript 7

### ISSUE THREAD

**Issue by nicmanzini** [triniwiz/nativescript-pager#186]
I believe the plugin broke again on NativeScript 7

because of the imports on this line

Error: Can't resolve '@nativescript/core/data/observable-array/observable-array'

line that can be found in the **pager.ios.ts**

I believe since NativeScript 7 everything can be imported directly from "@nativescript/core"

**Comment by sicbe** [comment]
Any ideas on how to fix this? I'm running into trouble with this as well...

**Comment by olaven** [comment]
I am also running into this.

**Comment by triniwiz** [comment]
Fixed in `@triniwiz/nativescript-pager`
