### ISSUE TITLE
Feature Request: Revamping swipeEnd events

### ISSUE THREAD

**Issue by JacobFJ** [triniwiz/nativescript-pager#193]
### Which platform(s) does your issue occur on?
-iOS
-Android

Framework Used: NS Vue

```
 **JS: Fire More!**
JS: {
JS:   "value": 4,
JS:   "selectedIndex": 4,
JS:   "object": {
JS:     "selectedIndex": 4
JS:   }
JS: }
**JS: Fire More!**
JS: {
JS:   "value": 5,
JS:   "selectedIndex": 5,
JS:   "object": {
JS:     "selectedIndex": 5
JS:   }
JS: }
**JS: Fire More!**
JS: {
JS:   "value": 6,
JS:   "selectedIndex": 6,
JS:   "object": {
JS:     "selectedIndex": 6
JS:   }
JS: }
**JS: Fire More!**
JS: {
JS:   "value": 7,
JS:   "selectedIndex": 7,
JS:   "object": {
JS:     "selectedIndex": 7
JS:   }
JS: }
```

Every time swiping to next index the swipeEnd firing as seen at **Fire More!** sample trigger in dynamic slides

It is similar to reachEnd from list and scroll view that handy for more data fetching from APIs.

PS: thanks for your plugin if this will be change that will be awesome..

**Comment by triniwiz** [comment]
If you are talking about a load more event there is already one `loadMoreItems` an even a way to set a count `loadMoreCount `
