### ISSUE TITLE
3 Pages in one view

### ISSUE THREAD

**Issue by NavruzbekNoraliev** [triniwiz/nativescript-pager#195]
How can I achieve a view that shows the little prev page and little end page and in the center active page, so it should have 3 pages in one view? 

[example](https://camo.githubusercontent.com/7590ec7e6b705a6e8e381397247d576c6db72147/68747470733a2f2f692e696d6775722e636f6d2f653157625a63752e676966)

**Comment by triniwiz** [comment]
Using peaking and spacing property they take px/dp/%

**Comment by NavruzbekNoraliev** [comment]
can you provide some code examples pls, I'm new to this framework and can't get it well
