### ISSUE TITLE
Not working in Angular 4 - NS 3

### ISSUE THREAD

**Issue by mrubkey** [triniwiz/nativescript-pager#20]
I have problem when run in emulator. it does not work. No error throw in console

**Comment by mrubkey** [comment]
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.GymStart",
    "tns-android": {
      "version": "3.0.0"
    }
  },
  "dependencies": {
    "@angular/animations": "~4.1.0",
    "@angular/common": "~4.1.0",
    "@angular/compiler": "~4.1.0",
    "@angular/core": "~4.1.0",
    "@angular/forms": "~4.1.0",
    "@angular/http": "~4.1.0",
    "@angular/platform-browser": "~4.1.0",
    "@angular/router": "~4.1.0",
    "@ngx-translate/core": "^6.0.1",
    "@ngx-translate/http-loader": "0.0.3",
    "locutus": "^2.0.8",
    "nativescript-angular": "~3.0.0",
    "nativescript-background-http": "^3.0.0",
    "nativescript-camera": "^3.0.0",
    "nativescript-fancyalert": "^1.1.2",
    "nativescript-imagepicker": "^3.0.0",
    "nativescript-loading-indicator": "^2.3.2",
    "nativescript-ngx-fonticon": "^2.2.0",
    "nativescript-pager": "^4.0.0",
    "nativescript-permissions": "^1.2.3",
    "nativescript-social-login": "^1.5.2",
    "nativescript-telerik-ui": "^2.0.1",
    "nativescript-theme-core": "~1.0.2",
    "nativescript-toolbox": "^1.49.2",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.3.0",
    "tns-core-modules": "~3.0.0",
    "tns-platform-declarations": "^3.0.1",
    "zone.js": "~0.8.2"
  },
  "devDependencies": {
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "~0.4.0",
    "typescript": "~2.2.1"
  }
}

**Comment by mrubkey** [comment]
JS: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
JS: ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'viewpagertransformers' of undefined
JS: TypeError: Cannot read property 'viewpagertransformers' of undefined
JS:     at Pager.set [as transformer] (file:///data/data/org.nativescript.GymStart/files/app/tns_modules/nativescript-pager/src/android/pager.js:133:53)
JS:     at ViewUtil.setPropertyInternal (file:///data/data/org.nativescript.GymStart/files/app/tns_modules/nativescript-angular/view-util.js:192:32)
JS:     at ViewUtil.setProperty (file:///data/data/org.nativescript.GymStart/files/app/tns_modules/nativescript-angular/view-util.js:155:18)
JS:     at EmulatedRenderer.NativeScriptRenderer.setAttribute (file:///data/data/org.nativescript.GymStart/files/app/tns_modules/nativescript-angular/renderer.js:126:30)
JS:     at DebugRenderer2.setAttribute (file:///data/data/org.nativescript.GymStart/files/app/tns_modules/@angular/core/bundles/core.umd.js:13218:23)
JS:     at createElement (file:///data/data/org.nativescript.GymStart/files/app/tns_modules/@angular/core/bundles/core.umd.js:9341:22)
JS:     at createViewNodes (file:///data/data/org.nativescript.GymStart/files/app/tns_modules/@angular/core/bundles/core.umd.js:11963:44)
JS:     at callViewAction (file:///data/data/org.nativescript.GymStart/files/app/tns_modules/@angular/core/bundles/core.umd.js:12381:13)
JS:     at execComponentViewsAction (file:///data/data/org.nativescript.GymStart/files/app/tns_modules/@angular/core/bundles/core.umd.js:12320:13)
JS:     at createViewNodes (file:///data/data/org.nativescript.GymStart/files/app/tns_modules/@angular/core/bundles/core.umd.js:12032:5)
JS:     at createRootView (file:///data/data/org.nativescript.GymStart/files/app/tns_modules/@angular/core/bundles/core.umd.js:11910:5)
JS:     at callWithDebugContext (file:///data/data/org.nativescript.GymStart/files/app/tns_modules/@angular/core/bundles/core.umd.js:13048:42)
JS:     at Object.debugCreateRootView [as createRootView] (file:///data/data/org.nativescript.GymStart/files/app/tns_modules/@angular/core/bundles/core.umd.js:12508:12)
JS:     at ComponentFactory_.create (file:///data/data/org.nativescript.GymStart/files/app/tns_modules/@angular/core/bundles/core.umd.js:9831:46)
JS:     at ComponentFactoryBoundToModule.create (file:///data/data/org.nativescript.GymStart/files/app/tns_modules/@angular/core/bundles/core.umd.js:3434:29)

**Comment by triniwiz** [comment]
Thanks this will be fixed soon :)

**Comment by diegomelo182** [comment]
i have the some error

**Comment by triniwiz** [comment]
Fixed https://github.com/triniwiz/nativescript-pager/commit/7d3312e193c391d6d292b43df319110edcf7a5cc
