### ISSUE TITLE
Issue with nativescript-angular@3.1.0

### ISSUE THREAD

**Issue by danielgek** [triniwiz/nativescript-pager#22]
The new version of nativescript-angular removes the `convertToInt` function from `nativescript/angular/utils` and it's used [here](https://github.com/triniwiz/nativescript-pager/blob/master/angular/index.ts#L9), i can make a pr but i can't have sure if the value still needs to be converted

@triniwiz any thoughts?

**Comment by triniwiz** [comment]
to be on the safe side convert it :)
