### ISSUE TITLE
Demo-ng: More than one view found in list template! Nesting level: 0

### ISSUE THREAD

**Issue by jogboms** [triniwiz/nativescript-pager#25]
tns --version: `3.1.1`
nativescript-angular: `3.1.1`
tns-core-modules: `3.1.0`

**Comment by Heer0** [comment]
This PR resolve it but is not yet merged.

https://github.com/triniwiz/nativescript-pager/pull/24

**Comment by triniwiz** [comment]
Upgrade to 5.0

**Comment by Heer0** [comment]
Great ! Thx !

**Comment by filipemendes1994** [comment]
I still have this problem, with 5.0 release and nativescript 3.1.  
Any thoughts?

**Comment by danielgek** [comment]
@triniwiz in nativescript-angular @sis0k0 made some changes that break this again

**Comment by sis0k0** [comment]
@danielgek, sorry about that. I'll fix this with a PR to this repo in a few hours.
