### ISSUE TITLE
Request: add documentation for "itemsLoading" event

### ISSUE THREAD

**Issue by lambourn** [triniwiz/nativescript-pager#32]
@triniwiz Nice work with the plugin. 

In my case I need to display different Views (both in terms of structure and functionality) inside the Pager so I cannot use a single itemTemplate.

While inspecting your code I noticed that the "itemsLoading" event can be used to provide a View reference "on-demand" to the Pager.

Would be great if you could add this functionality to the README

**Comment by triniwiz** [comment]
You can use multiple templates now reopen if you still need this
