### ISSUE TITLE
Question: Is it possible to show multiple slide ?

### ISSUE THREAD

**Issue by dotnetdreamer** [triniwiz/nativescript-pager#34]
Hi,
Currently we can see now one slide in whole screen. Is it possible to show previous and next slide too ? i mean 3 slide at a time ?

**Comment by FranciZ** [comment]
@triniwiz Is there a way to implement this now?

**Comment by triniwiz** [comment]
You need to add `spacing=“2%” peaking=“10%”`

**Comment by FranciZ** [comment]
Thanks! I have to call `this.pager.nativeElement.refresh();` after to get it to work. Before then it's a little broken like in the attached gif.

![ezgif-5-4d610ad6ec9a](https://user-images.githubusercontent.com/2536035/49338498-123b5780-f622-11e8-8daf-528dc6eb4b61.gif)

**Comment by triniwiz** [comment]
@FranciZ what version are you using core , angular , vue also what {N} version

**Comment by FranciZ** [comment]
Angular: 7.0.7
tns --version: 5.0.2
tns-android: 5.0.0
tns-core-modules: 5.0.5
