### ISSUE TITLE
Angular issues

### ISSUE THREAD

**Issue by jdnichollsc** [triniwiz/nativescript-pager#35]
Hi @triniwiz,
Remember the issues with Angular:
- This shows an error when initialize the first time **Page.items not set**
- The image of the first slide does not load
![pager-issue](https://user-images.githubusercontent.com/2154886/33131841-cda6bbe8-cf65-11e7-9223-cfe4cef3efd1.gif)

Thanks for this very useful component!
Nicholls

**Comment by triniwiz** [comment]
For a quick fix as @sean-perkins mentioned you can call `_initNativeViewPager()` from the page instance to fix the initial load problem

**Comment by jdnichollsc** [comment]
@triniwiz but it's a temporal solution, right? @sean-perkins can you paste your solution here to help others with the same issue? thanks guys!

**Comment by triniwiz** [comment]
Yes a temp solution 😊

**Comment by jdnichollsc** [comment]
I lost the temporal solution of @sean-perkins 🙈

**Comment by jdnichollsc** [comment]
For the moment the solution is using a ng-container with an Observable array:
```
<ng-container *ngIf="(images | async)?.length > 0">
    <Pager [items]="images | async" #pager class="pager">
        <ng-template pagerItemTemplate let-i="index" let-item="item">
            <GridLayout class="pager-item" rows="auto, *" columns="*" backgroundColor="red">
                <Label [text]="item.title"></Label>
                <Image row="1" [src]="item.image"></Image>
            </GridLayout>
        </ng-template>
    </Pager>
</ng-container>
```

Thanks guys and thank you so much @sean-perkins for your help!

**Comment by jdnichollsc** [comment]
Guys, by the other hand... My app is crashing when I use the following configuration from the template:
```
[selectedIndex]="currentPagerIndex" (selectedIndexChange)="onIndexChanged($event)"
```

Let me know what you think, thanks in advance! 👍

**Comment by jdnichollsc** [comment]
For the moment I'm using a variable `loadingImages` with the ng-container to reload the component, because the selectedIndex doesn't work

**Comment by triniwiz** [comment]
Fixed in v7

**Comment by jdnichollsc** [comment]
Woww thanks @triniwiz, let me check! 👍
