### ISSUE TITLE
The event `selectedIndexChanged` doesn't work on v5.0.10

### ISSUE THREAD

**Issue by ogrinishin** [triniwiz/nativescript-pager#36]
It seems to me, that the line 
`pager.notify({ eventName: Pager.selectedIndexChangedEvent, object: pager, oldIndex: oldValue, newIndex: newValue });`
after 60 line in file
`node_modules\nativescript-pager\src\common.js`
is lost.
Because without it the event `selectedIndexChanged` isn't triggered. Can you please fix it in your plugin?

**Comment by triniwiz** [comment]
it's `selectedIndexChange` not `selectedIndexChanged` in {N} v3 the the events names moved from `changed` to `change`

**Comment by ogrinishin** [comment]
@triniwiz 
I tried to change but it is still broken, additionally there is not `selectedIndexChange` event in the npm,
 look at the screen [http://prntscr.com/hktj2w](url)

**Comment by triniwiz** [comment]
The following is how the event gets triggered [ios event](https://github.com/triniwiz/nativescript-pager/blob/master/src/ios/pager.ts#L237)
[android event](https://github.com/triniwiz/nativescript-pager/blob/master/src/android/pager.ts#L251) or [other android event](https://github.com/triniwiz/nativescript-pager/blob/master/src/android/pager.ts#L86) check out [why i removed selectedIndexChanged ](https://github.com/NativeScript/NativeScript/blob/master/Modules30Changes.md#events-raised-when-property-value-change) to use the default `propertyName + Change` from the new property modules i can probably add in for backwards compatibility
