### ISSUE TITLE
Pager Indicator Support

### ISSUE THREAD

**Issue by maddy2get** [triniwiz/nativescript-pager#4]
Is there a possibility to add support for pager indicator like in HTML slideshow (dots at the bottom) indicating which pagerView you are on? And if that can be another customisable view, that would be great.

**Comment by arnauvp** [comment]
@maddy2get It seems you could possibly write your own reading the `pager.items.length` and `pager.selectedIndex`, and dock it at the bottom like the buttons from the demo or overlay them with an AbsoluteLayout ?

**Comment by triniwiz** [comment]
yeah @arnauvp is right this way you can create some awesome indicators with animations ;)
