### ISSUE TITLE
Multitemplate Angular, only default template is displayed

### ISSUE THREAD

**Issue by farzeni** [triniwiz/nativescript-pager#43]
### Which platform(s) does your issue occur on?
Tryed on Android but probably affects both

### Please, provide the following version numbers that your issue occurs with:

- CLI: 3.4.1
- Cross-platform modules: 3.4.0
- Runtime(s): 3.4.1
- Plugin(s): nativescript-pager 7.0.12,

### Please, tell us how to recreate the issue in as much detail as possible. 
Hello @triniwiz,

When I try to create a multitemplate pager in a angular app on android platform, templates are ignored and just the first one is picked up.

I debugged a little bit your plugin and I noted that _pagerTemplateKey_ are correctly parsed and _registerTemplate_ method is called. The problem is that _registerTemplate_ fills __templateMap_ variable but internally pager uses _itemTemplates_ property to look for registered templates which is filled by _setItemTemplates_. But the latest is never called when a new template is registered.

I added a call to _setItemTemplates_ at the end of _registerTemplate_ and things seem to work again, but I'm not sure it is the right solution, maybe you can tell me something better.

Here is what i changed:
https://github.com/farzeni/nativescript-pager/commit/fd3b5251ddbecdf4f70590c8d81102d35b31a8a0

Thank you for your work

**Comment by triniwiz** [comment]
Good catch 😄
