### ISSUE TITLE
How to show absoluteLayout over pager --closed

### ISSUE THREAD

**Issue by MuhammadTahir92** [triniwiz/nativescript-pager#45]
_```
<GridLayout rows="auto,*,auto" columns="*" class="page">

    <AbsoluteLayout style="margin-top:50;">
        
        <GridLayout    left="0" top="50" rows="auto" backgroundColor="yellow" top="20" columns="*,*,*,*,*,*,*">
            <Label text="This text should be on top of pager" ></Label>
        </GridLayout>
    </AbsoluteLayout>
    
    <Pager  row="1" [items]="items | async" #pager (selectedIndexChange)="onIndexChanged($event)" class="pager" backgroundColor="lightsteelblue">
        <ng-template let-i="index" let-item="item">
            <GridLayout rows="*" columns="*">
                <StackLayout orientation="vertical" backgroundColor="red">
                    <Label class=" h6" style="font-size:13;" [text]='item.title'></Label>
                </StackLayout>
            </GridLayout>
        </ng-template>
    </Pager>
</GridLayout>``
```_

**Comment by farzeni** [comment]
@MuhammadTahir92 

best way to do this:

```
<GridLayout rows='*' columns='*'>
   <Label text="This text should be on top of pager" style='margin-top:50;'></Label>
   <Pager  row="1" [items]="items | async" #pager (selectedIndexChange)="onIndexChanged($event)" class="pager" backgroundColor="lightsteelblue">
      <ng-template let-i="index" let-item="item">
        <GridLayout rows="*" columns="*">
            <StackLayout orientation="vertical" backgroundColor="red">
                <Label class=" h6" style="font-size:13;" [text]='item.title'></Label>
            </StackLayout>
        </GridLayout>
      </ng-template>
  </Pager>
</GridLayout>

```

**Comment by MuhammadTahir92** [comment]
Thanks @farzeni
