### ISSUE TITLE
Change to items bound ObservableArray does not update views

### ISSUE THREAD

**Issue by PeterStaev** [triniwiz/nativescript-pager#46]
Having the plugin bound to an `ObservableArray`. If you change the bound property the plugin is not refreshed. Also on Android if you try to scroll you get an exception. This is because for the value change of the `itemsProperty` you need to have a check and if an` ObservableArray` to add an event listener so when it is updated to trigger a refresh of the plugin. Here is how I have it in the GridView plugin:
https://github.com/PeterStaev/NativeScript-Grid-View/blob/8b6120195e82d9918c11a2af1dc003566b22fe69/grid-view-common.ts#L86-L103

Attaching here a sample app. On button tap the bound property is changed to have 2 items. 
[pager-observable.zip](https://github.com/triniwiz/nativescript-pager/files/1740941/pager-observable.zip)

**Comment by triniwiz** [comment]
Thanks man 😁
