### ISSUE TITLE
[Android] Pager multiple itemTemplates do not work when dynamically loading data

### ISSUE THREAD

**Issue by PeterStaev** [triniwiz/nativescript-pager#47]
So I have an `ObservableArray` that is first initialized with `null` values. Then when the index of the pager is changed I'm loading data from the backend and replacing the `null` value with the appropriate `Observable` model object for the view. I'm having 2 different templates - one that is for `null` object and one for non-null objects. After the data is loaded and I replace the `null` object it still shows the blank template for the item. From what I've traced this is due to two problems:
1. The code in the `instantiateItem` does not take into consideration the template, it is just based by index:
https://github.com/triniwiz/nativescript-pager/blob/558f1b2a7ad30db5e0b9b69f2bbb8a07383f98a0/src/pager.android.ts#L304-L312
This can easily be fixed by instead using just the `position` to use `${position}-${template.key}` as the key for the cached view map. 
2. (The bigger one) Although when an item in the `ObservableArray` is changed the `refres()` methos is correctly called but the adapter's `notifyDataSetChanged()` does **not** cause the views to be regenerated. So basically it does nothing... You can read more about the possible solutions here: https://stackoverflow.com/a/7287121/5272836.

**Comment by triniwiz** [comment]
Great suggestions @PeterStaev
