### ISSUE TITLE
Pager bugs on iOS with Angular

### ISSUE THREAD

**Issue by ddfreiling** [triniwiz/nativescript-pager#5]
1. If selectedIndex is not set on Pager, it will simply not work and crash on swipe. It should probably default to 0.

2. Using Angular and on iOS if I set selectedIndex without binding it, the first selected page will show "Pager.items not set", until you change page to another and back again.

3. It seems that binding the selectedIndex property and changing it from code does not work on iOS, it doesn't change page to the new index. Works on Android.

**Comment by maddy2get** [comment]
4. First page does not load properly until you swipe to next page and come back on iOS
