### ISSUE TITLE
Manual page change is not animated in ios

### ISSUE THREAD

**Issue by kwidzinskidawid** [triniwiz/nativescript-pager#50]
### Which platform(s) does your issue occur on?
- iOS
- emulator and device

### Please, provide the following version numbers that your issue occurs with:

- CLI: 3.4.1
- Cross-platform modules: 3.4.0
- Runtime(s): 3.4.0
- Plugin(s): 7.1.3

### Please, tell us how to recreate the issue in as much detail as possible. 

When manually (programmatically) setting current pager index, pager instantly changes page to new index, without transition.
On android page change is smoothly animated.

Example gif in readme [here](https://camo.githubusercontent.com/8b0666f485693c324136367b8696242a88c3886b/68747470733a2f2f692e696d6775722e636f6d2f6d766b71584f612e676966) suggests that switching pages should be animated (clicking previous and next page). I tried downloading demo but its the same thing. Pages are instantly changed without transition.

**Comment by triniwiz** [comment]
Yeah i disabled it -> [here](https://github.com/triniwiz/nativescript-pager/blob/master/src/pager.ios.ts#L385) at the time of debuging a crash that seemed to becausing problems i can look at it again or if you want to test it change it to true LMK how it works 😄

**Comment by kwidzinskidawid** [comment]
Thanks for a quick response. Yes, changing that third parameter to true fixes it. I tested it on an emulator and on a device and everything seems fine. Do you think you could look at it again to see if it really causes any trouble? Or if its too much trouble, maybe make that boolean variable as a pager attribute that defaults to false so i can turn those animations at my own responsibility :smile:

**Comment by triniwiz** [comment]
so now it's enabled by default use `disableAnimation="true"` if you don't need it

**Comment by kwidzinskidawid** [comment]
Thanks for a quick change, everything looks great except animations are working when disabledAnimation is set to true.
I guess [here](https://github.com/triniwiz/nativescript-pager/commit/b0a21010108e4475e6542d7a7075ae08403fcb86#diff-d7ea0f9f65663221f83197bf2c15aa16R392) has to be !this.disableAnimation, since the argument says if the animations are enabled

**Comment by triniwiz** [comment]
lol my bad (rushing to get it complete) 😂
