### ISSUE TITLE
Cannot use in nativescript-vue

### ISSUE THREAD

**Issue by hoatructhanhlam** [triniwiz/nativescript-pager#51]
I emplement via references but get a error message 
``` 
System.err: Error: com.tns.NativeScriptException: Failed to find module: "vue/pager", relative to: app/tns_modules/
```

**Comment by triniwiz** [comment]
Code ?

**Comment by hoatructhanhlam** [comment]
Error with simple code
```
import Vue from 'nativescript-vue';
import Pager from 'nativescript-pager/vue';
Vue.use(Pager);
```
I'm doing with vue-cli-template latest

**Comment by triniwiz** [comment]
Yeah that weird the last version of that template I tested the plugin with you can check the demo-vue

**Comment by hoatructhanhlam** [comment]
It already run ok in nativescript-vue 1.3.0. However, in version 1.3.1 i get error message
```
ERROR in app.android.js from UglifyJs
Unexpected token: punc ()) [app.android.js:38659,38]
```
...........
and after
```
System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 
System.err: Error calling module function 
System.err: Error: com.tns.NativeScriptException: Failed to find module: "vue/pager", relative to: app/tns_modules/
```

**Comment by 7ammer** [comment]
I am getting this issue too.

import Vue from 'nativescript-vue';
import Pager from 'nativescript-pager/vue';
// import Pager from '../node_modules/nativescript-pager/vue'; // doesn't work either
Vue.use(Pager);


ERROR in app.ios.js from UglifyJs
Unexpected token: punc ()) [app.ios.js:13666,38]

file:///app/app.js:13681:25: JS ERROR Error: Could not find module 'vue/pager'. Computed path '/Users/jamesisbell/Library/Developer/CoreSimulator/Devices/DE8DFB88-DC71-4F2C-94E9-377AC5A8C60D/data/Containers/Bundle/Application/61EE2861-820A-4033-AAFF-4F7D4DED947D/dist.app/app/tns_modules/vue/pager'.

**Comment by triniwiz** [comment]
it's looking in the wrong path `Could not find module 'vue/pager'` is that the cli template ?

**Comment by 7ammer** [comment]
I've also tried this...

```
Vue.registerElement('NativePager', () => require('nativescript-pager').Pager);
Vue.component('Pager', require('nativescript-pager/vue/pager')(Vue));
```

`ERROR in app.ios.js from UglifyJs - Unexpected character ‘`’ [app.ios.js:16863,14]`
This error seems to be an issue with using ‘`’ style quotes for inline templates.

**Comment by triniwiz** [comment]
Some code would be nice to replicate 🙂

**Comment by 7ammer** [comment]
Alrighty, I'll setup a git repo soon...

**Comment by altunyurt** [comment]
I'm also having the same Failed to find module: "vue/pager", relative to: app/tns_modules/
error. For now a simple solution is as @7ammer  mentioned:

    Vue.registerElement('NativePager', () => require('nativescript-pager').Pager);
    Vue.component('Pager', require('nativescript-pager/vue/pager')(Vue))
   

@7ammer for the punc()) error, you'll need to upgrade uglifyjs-webpack-plugin in webpack node_modules. Then edit your webpack.config.js to contain this: 

     const UglifyJsPlugin = require('uglifyjs-webpack-plugin')
      // Minify JavaScript code
      //new webpack.optimize.UglifyJsPlugin({
      new UglifyJsPlugin({
        parallel: true,
        uglifyOptions: {
            compress: {warnings: false},
            output: {comments: false},
        }
      }), 

which i guess will also solve the problem you've faced implementing the solution above.
