### ISSUE TITLE
[ios] selectedIndex binding does not work

### ISSUE THREAD

**Issue by PeterStaev** [triniwiz/nativescript-pager#52]
Under iOS if you bind `selectedIndex` to some model property it never selects the correct page. It just shows a blank screen. Once you try to swipe back/forth the content shows. Under android this works as expected. 

Here is a playground demonstrating the problem: https://play.nativescript.org/?template=play-tsc&id=VfBiYQ

**Comment by triniwiz** [comment]
can you try adding `disableAnimation="true"` to the element and tell me how that goes

**Comment by PeterStaev** [comment]
@triniwiz , this indeed worarounds the issue 👍

**Comment by triniwiz** [comment]
The new version also includes a fix for that so the `disableAnimation` is no longer needed
