### ISSUE TITLE
Three time call ngOninit in IOS

### ISSUE THREAD

**Issue by AsrarMemon** [triniwiz/nativescript-pager#56]
i am try this code 

```
items = [1, 2, 3];
    public templateSelector = (item: any, index: number, items: any) => {
        return index % 2 === 0 ? 'even' : 'odd';
        if (index === 0) {
            return 'first';
        } else if (index === 1) {
            return 'second';
        } else if (index === 2) {
            return 'third';
        }
    };
```

```
<Pager [items]="items" [itemTemplateSelector]="templateSelector">

    <ng-template pagerTemplateKey="first" let-i="index" let-item="item">
        <StackLayout height="100%">
            <router-outlet height="100%"></router-outlet>
        </StackLayout>
    </ng-template>

    <ng-template pagerTemplateKey="second" let-i="index" let-item="item">
        <StackLayout height="100%">
            <router-outlet name="Graph"></router-outlet>
        </StackLayout>
    </ng-template>

    <ng-template pagerTemplateKey="third" let-i="index" let-item="item">
        <router-outlet name="DataList"></router-outlet>
    </ng-template>

</Pager>
```

in IOS when pager Initialize at that time  three or four time call ngOnInit of first component and
second  component 
then i go to second  component at that time call third component ngOninit 
then never call ngOnint or ngOnDestroy  of any component any swipe of page 

so how can i known which component is on view 

it is also very difficulty to handle different behaviour in Android and IOS
so can you please help me out ?

**Comment by triniwiz** [comment]
You can use `loaded` and `unloaded` on the parent component

**Comment by AsrarMemon** [comment]
yes but i am load 20 or more component in Pager and each component have setInterval
so i just need to when current View is Load start Interval And the clear Interval
and each have different work base on that  component requirement 

i still not known how to i achieve this
