### ISSUE TITLE
loads only the next and the prev pages

### ISSUE THREAD

**Issue by shabib3** [triniwiz/nativescript-pager#57]
Hi,

I am implementing a times picker flow with this pager plugin and I found out that the pager loads only the next and the previous pages, and when I move to two pages a head the first page just get destroyed...
here is a video sample -> https://youtu.be/UaQV7X9wr9I

I tested it only on Android...

Any idea about this? :)

**Comment by shabib3** [comment]
@alexandruantonica 

just out `pagesCount` attribute in the element

**Comment by triniwiz** [comment]
That’s androids default behavior you can use the `pagesCount` prop to increase the limit
