### ISSUE TITLE
items array changed - IOS rendering issue

### ISSUE THREAD

**Issue by shabib3** [triniwiz/nativescript-pager#58]
Happen only on IOS

There is a bug on IOS rendering.
I want to create a Pager on changed array and it seems that this is an issue with rendering...it takes you the the second page and also black the page, so I should swipe left or right to get it live agian
I think example would be the best to describe it:

*** NS-Angular

TS:
```
import { Component } from "@angular/core";

@Component({
    moduleId: module.id,
    selector: "times-selection",
    templateUrl: "./timesSelection.component.html"
})
export class TimesSelectionComponent {
    public selectedDates: Array<Date> = [];

    constructor() {
        setTimeout(() => {
            this.selectedDates = [new Date(), new Date()];
        }, 5000)
    }
}
```

HTML:
```
<Pager [items]="selectedDates" width="100%" height="100%" [pagesCount]="selectedDates.length">
    <ng-template let-item="item">
        <GridLayout rows="*" columns="*">
            <Label width="100%" row="0" col="0" textAlignment="center" [text]="item"></Label>
        </GridLayout>
    </ng-template>
</Pager>
```

but you can see that if you define the `selectedDates` in the beginning just like this `public selectedDates: Array<Date> = [new Date(), new Date()];` it will work.

any idea why?

**Comment by triniwiz** [comment]
Can you try adding the `disableAnimation="true"` to the page and report the new findings ?

**Comment by shabib3** [comment]
Works perfectly! Thank you!
