### ISSUE TITLE
selectedIndexChanged and multi template does not work in my project

### ISSUE THREAD

**Issue by alexandruantonica** [triniwiz/nativescript-pager#59]
Hi @triniwiz 

I have [here](https://play.nativescript.org/?template=play-ng&id=BFmIwn&v=3) an example of implementation where the latest version doesn't work properly and I don't know what is wrong. 
Can you take a look, please ?

**Comment by triniwiz** [comment]
First it's `selectedIndexChange` and not `selectedIndexChanged` https://github.com/triniwiz/nativescript-pager/blob/master/demo-ng/app/test/test.component.html#L6 also you can try the demo see if that can help if not i'll run some tests later

**Comment by alexandruantonica** [comment]
I found it. 
`$event.value` instead of `$event.oldIndex` 
It was my mistake.
