### ISSUE TITLE
more control over the slide

### ISSUE THREAD

**Issue by hamdiwanis** [triniwiz/nativescript-pager#64]
is there any way I can control if the pager can go to the next screen?

**Comment by triniwiz** [comment]
There is the disableSwipe prop

**Comment by hamdiwanis** [comment]
i want to disable it on next only but allow it to go back
i think canScrollHorizontally on ViewPager will do it no android side
thanks for the reply :)

**Comment by hamdiwanis** [comment]
i was able to to make this behaviour by overriding the pager adapter getCount 
this.pager.nativeElement.pagerAdapter.getCount = () => 2;
this.pager.nativeElement.pagerAdapter.notifyDataSetChanged();
but i think overriding the canScrollHorizontally fn of the view pager will be better solution

**Comment by hamdiwanis** [comment]
i did a PR with this take a look when you have time :)
