### ISSUE TITLE
Dynamic data for pager

### ISSUE THREAD

**Issue by HoangJK** [triniwiz/nativescript-pager#66]
When I push data into itemData, pager update view is right. But when I unshift item in itemData, pager update view wrong.

**Comment by triniwiz** [comment]
try calling `.refresh(true)` on the pager

**Comment by HoangJK** [comment]
I try .refresh(true), but it not working.
I have items = [1, 2, 3], Pager show 3 page, it ok.
I use items.unshift(0); this.pager.nativeElement.refresh(true) ;
console.log(items) => [0, 1, 2, 3]
But Pager show: 0 - 1 - 3 - 3
Can you check this issue?

**Comment by HoangJK** [comment]
I try call unshift into setTimeout(); It run ok for me. But I don't know why.

**Comment by HoangJK** [comment]
It seem problem when Pager gender view when unshift data in to items.
