### ISSUE TITLE
insert/remove objects with array.splice doesn't work fine IOS

### ISSUE THREAD

**Issue by LauraNavarroGalvan** [triniwiz/nativescript-pager#67]
I'm trying to insert an object in a certain index and eliminating a specific object depending on what I need, but this does not work well in IOS. my variable BehaviorSubject is fine but in the view it doesn't appear as it should. this is my code:

if (checkboxOption.trigger && checkboxOption.option_selected == true) {
let trigger = []; 
			trigger = this.getCorrectStructureForm(checkboxOption.trigger);
			let newItems = (<BehaviorSubject<any>>this.formItems).value;
			trigger.forEach(newQuestion => {
				newItems.splice(indexPage+1, 0, newQuestion);
			});
			this.formItems.next(newItems);
			this.numItems = this.formItems.value.length;
		} else if(checkboxOption.trigger && checkboxOption.option_selected == false) {
			let removeItems = (<BehaviorSubject<any>>this.formItems).value;
			checkboxOption.trigger.forEach(removeQuestion => {
				let indexRemove = removeItems.findIndex(item => item.fuid === removeQuestion.fuid);
				removeItems.splice(indexRemove, 1);
			});
			this.formItems.next(removeItems);
			this.numItems = this.formItems.value.length;
		}

**Comment by triniwiz** [comment]
Are you using this.numItems anywhere in the view?

**Comment by LauraNavarroGalvan** [comment]
yes, I use this to calculate the number of pages and to change the buttons that are displayed in the view

**Comment by triniwiz** [comment]
So it’s the buttons that doesn’t update no?

**Comment by LauraNavarroGalvan** [comment]
no, the problem is not the buttons, the problem is when I insert an object in the middle of two pages, the new object it is shown in another part or with wrong information (usually duplicates the last page) and when I delete an object always removes me the last page. however when I review the BehaviorSubject object in the console, this is fine but in the view not and this only happens in ios.

**Comment by triniwiz** [comment]
Can you try calling .refresh(true) on the pager after you update it ?

**Comment by HoangJK** [comment]
@triniwiz 
I think I have same problem #66 
When I use unshift in items, it update wrong data in Pager.

**Comment by HoangJK** [comment]
I have items = [1, 2, 3], Pager show 3 page, it ok.
I use items.unshift(0); this.pager.nativeElement.refresh(true) ;

console.log(items) => [0, 1, 2, 3]

But Pager show data: 0 - 1 - 3 - 3

**Comment by LauraNavarroGalvan** [comment]
it still doesn't work @triniwiz

**Comment by LauraNavarroGalvan** [comment]
if I refresh the items as shown in the code below, it works, but the UX is ugly, because the previous page is first displayed and then the new page.
for example if I have items = [1,2,3]
and I update it to items = [1,2, new, 3]
First he shows me page 3 and after a few seconds the new page is shown, which makes the user thing as an error.
```
prevPage() {
	this.pager.nativeElement.refresh(true);
	const newIndex = Math.max(0, this.currentPagerIndex - 1);
	this.currentPagerIndex = newIndex;
	this.pager.nativeElement.selectedIndex = newIndex;
}

// Go to the next page
nextPage() {
	this.pager.nativeElement.refresh(true);
	const newIndex = Math.min(this.numItems - 1, this.currentPagerIndex + 1);
	this.currentPagerIndex = newIndex;
	this.pager.nativeElement.selectedIndex = newIndex;
}

// Change de Index of the page
onIndexChanged($event) {
	this.pager.nativeElement.refresh(true);
	this.latestReceivedIndex = $event.value;
	this.currentPagerIndex = $event.value;
}
addQuestion() {
	let newItems = (<BehaviorSubject>this.formItems).value;
	newItems.splice(indexPage+1, 0, newQuestion);
	this.formItems.next(newItem);
	this.numItems = this.formItems.value.length;
}
```

**Comment by triniwiz** [comment]
Thanks for the info 😃

**Comment by triniwiz** [comment]
Can you try the latest version :)

**Comment by triniwiz** [comment]
This is fixed in the latest release
