### ISSUE TITLE
TextField focus keyboard screen overlay issue when using Pager

### ISSUE THREAD

**Issue by FranciZ** [triniwiz/nativescript-pager#73]
### Which platform(s) does your issue occur on?
- Android
- 8.1
- Pixel XL 2

### Please, provide the following version numbers that your issue occurs with:

- CLI: 4.1.2
- Cross-platform modules: 4.0.1
- Runtime(s): 4.1.3

### Please, tell us how to recreate the issue in as much detail as possible. 
Add a `Pager` to a view and then add a `TextField` either as a page in a pager or just somewhere next to the pager. Then focus on `TextField` does not reposition the screen any more to make sure the `TextField` stays in view.

If not using `Pager` the screen repositions correctly to make sure the `TextField` remains in view once focused. But adding the `Pager` it breaks that functionality.

**Comment by FranciZ** [comment]
Noticed this issue does not happen on an older Android 4.4.4, while it does on 8.1.

**Comment by triniwiz** [comment]
Does this still happen in the latest version ?

**Comment by hcgustavo** [comment]
This is also happening to me. I'm using the last version of the plugin.

**Comment by romandragan** [comment]
It's happening for me as well on the latest `13.0.0-alpha.12`.
