### ISSUE TITLE
NativeScript-vue support is broken in the NS-vue 2.0.0-alpha version

### ISSUE THREAD

**Issue by msaelices** [triniwiz/nativescript-pager#74]
I guess the only change needed is changing the `<native-pager>` tag name to `<NativePager>` one here:

https://github.com/triniwiz/nativescript-pager/blob/master/src/vue/pager.js#L26

**Comment by msaelices** [comment]
CC/ @rigor789

**Comment by rigor789** [comment]
Have you tried it? I think `native-pager` should still work, since vue can resolve it to `NativePager`

**Comment by msaelices** [comment]
@rigor789 Yes I tried and there is an exception
