### ISSUE TITLE
More events for swipe

### ISSUE THREAD

**Issue by alexandruantonica** [triniwiz/nativescript-pager#77]
### Feature
Hi @triniwiz 

Can we have something similar with [drag&drop events](https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API) for swipe in Pager ? 
Will be very interesting to have : 
- `swipe` : fired when a slide is being swiped (similar with `selectedIndexChange`) 
- `swipestart` : fired when the user tapped on the slide to swipe
- `swipeover` (during the swipe) : fired when the user swipe the slide, in between `swipestart` and `swipeend` 
- `swipeend` : fired when the swipe operation is being ended

### Motivation
I believe it will be very useful for those who wants to create interesting animation of transition (eg. tutorials) when you have a Pager & some static elements in your page and want to hide the static element on some slides. 
We can do this now but the show/hide events is fired after the Pager changes the `selectedIndex` and the transition looks a bit delayed.

**Comment by triniwiz** [comment]
Nice i'll look into it

**Comment by triniwiz** [comment]
The following events has been added to the pager element ```
swipe=""
swipeStart=""
swipeOver=""
swipeEnd=""
```
