### ISSUE TITLE
Showing empty <Label> instead of Slide Content (Angular 6)

### ISSUE THREAD

**Issue by alereisan** [triniwiz/nativescript-pager#79]
Showing empty `<Label>` instead of Slide Content (Angular 6)

**Comment by triniwiz** [comment]
1. Which platform
2. All slides or the first

**Comment by alereisan** [comment]
Android and all Slides

Osei Fortune <notifications@github.com> schrieb am So., 14. Okt. 2018,
16:48:

**Comment by mailiam** [comment]
also occurs on iOS 12
It only shows view like `<Label [text]="item">`

```html
<Pager row="0" timetable
  [items]="availableTimetable.weekdays">
  <ng-template pagerItemTemplate let-i="index" let-day="item">
    <GridLayout times flexWrap="wrap"
      iosOverflowSafeArea="false">
      <StackLayout orientation="horizontal">
        <Button text="{{ '\ue080' }}"></Button>
        <Label text="{{day}}"></Label>
      </StackLayout>
      <FlexboxLayout class="part" flexWrap="wrap" 
        [width]="cardWidth" iosOverflowSafeArea="false"
        *ngFor="let part of availableTimetable.times">
        <ng-template ngFor let-time let-j="index" let-even="even" [ngForOf]="part">
          <Button text="{{ '\ue080' }}" [flexWrapBefore]="even"></Button>
          <Label  flexGrow="1" [text]="time"></Label>
        </ng-template>
      </FlexboxLayout>
    </GridLayout>
  </ng-template>
</Pager>
```

**Comment by mailiam** [comment]
It looks like PagerComponent constructor is not even called. 
I will take a deeper look into the problem

**Comment by mailiam** [comment]
The problem lied on `setItemTemplates` that it is called when content is not yet initialized.

Calling  `setItemTemplates` in  `ngAfterContentInit` solved the issue.

NativeScritpt/nativescript-angular has refactored [ListView](https://github.com/NativeScript/nativescript-angular/blob/master/nativescript-angular/directives/list-view-comp.ts
) to extend [TemplatedItemsComponent](https://github.com/NativeScript/nativescript-angular/blob/master/nativescript-angular/directives/templated-items-comp.ts)

I suggest `nativescript-pager` can also benefit from extending `TemplatedItemsComponent`

@triniwiz what do you think?

**Comment by triniwiz** [comment]
@mailiam i've started https://github.com/triniwiz/nativescript-pager/tree/v9 you can test and lmk how things are running

**Comment by mailiam** [comment]
> @mailiam i've started https://github.com/triniwiz/nativescript-pager/tree/v9 you can test and lmk how things are running

I should've looked into latest commits. 
It works as expected!

**Comment by triniwiz** [comment]
@mailiam i'm exploring `android.support.v4.app.FragmentStatePagerAdapter` before I release v9 to see if I can squeeze some performance out

**Comment by mailiam** [comment]
Great! looking forward for v9 public release.
Thanks for awesome plugin.
