### ISSUE TITLE
Multi template not working in 9.x?

### ISSUE THREAD

**Issue by FranciZ** [triniwiz/nativescript-pager#84]
Tried to get it to work in Android and iOS. Neither seems to work as I used to expect.

Prepared a small playground example. Playground errors on my Android for some reason but works on iOS, not the multi template though. If I build locally multi template fails on android as well. Only the first/default template is ever displayed.

https://play.nativescript.org/?template=play-ng&id=gpnalf

Angular: 7.0.7
tns --version: 5.0.2
tns-android: 5.0.0
tns-core-modules: 5.0.5

**Comment by triniwiz** [comment]
fixed -> https://github.com/triniwiz/nativescript-pager/commit/2528de5bc86007a63c4c8b4861cc9d1c4456c701
