### ISSUE TITLE
AOT Breaks 9.x

### ISSUE THREAD

**Issue by FranciZ** [triniwiz/nativescript-pager#85]
Works until built with AOT. Then it complains that `PagerModule` is missing `@NgModule()`. If I add the `@NgModule()` in `nativescript-pager/angular/index.d.ts` it does build, but pager slides show as `[object Object]`. As if the import was missing, but it is not.

Angular: 7.0.7
nativescript-pager: 9.0.2
tns --version: 5.0.2
tns-android: 5.0.0
tns-core-modules: 5.0.5

**Comment by triniwiz** [comment]
fixed in the the new release `v9.1.0`
