### ISSUE TITLE
get a peek of sibling pager items?

### ISSUE THREAD

**Issue by robertoandres24** [triniwiz/nativescript-pager#92]
There is some way to get a peek of the adjacent elements, like in the next picture?

![image](https://user-images.githubusercontent.com/11506518/50495539-7c200480-0a08-11e9-84a5-95327e6080f0.png)

**Comment by exeleon** [comment]
@robertoandres24 @alexandruantonica 
You can use `spacing="2%" peaking="10%"` as explained in #34 

I had to force refresh after Pager load:

HTML:
`
<Pager (loaded)="onPagerLoaded($event)" spacing="7%" peaking="8%">
`

TS:
```
import { Pager } from 'nativescript-pager';

onPagerLoaded(event: any) {
  setTimeout(() => (<Pager>event.object).refresh());
}
```

**Comment by exeleon** [comment]
> You can use `%` , `px` it defaults to`dips`

Hi @triniwiz , thanks a lot for this awesome plugin!

Do you know why we have to force refresh to this setting taking place?

**Comment by triniwiz** [comment]
You shouldn’t need to force a refresh again 🙂
