### ISSUE TITLE
console warning in iOS

### ISSUE THREAD

**Issue by racknoris** [triniwiz/nativescript-pager#97]
After placing a pager in Nativescript 5.2 angular application, in iOS, I got:
`CONSOLE WARN file:///app/tns_modules/nativescript-pager/pager.js:435:56: Class "UICollectionDelegateImpl" already implements the "UIScrollViewDelegate" protocol.`

**Comment by glennsyang** [comment]
I got the same message, and the app crashes. I'm using NS 5.2

**Comment by triniwiz** [comment]
It should be working on the latest

**Comment by racknoris** [comment]
@triniwiz along with that error, when I turned pages, they sometimes got stuck in the middle. Will the fix solve this as well?

**Comment by triniwiz** [comment]
@racknoris a gif would be nice to see the behavior
