### ISSUE TITLE
App crashes when scrolling to dynamically added item [Vue]

### ISSUE THREAD

**Issue by tweichart** [triniwiz/nativescript-pager#98]
### Which platform(s) does your issue occur on?

- iOS
- iOS 12.1 (emulator)
- emulator

### Please, provide the following version numbers that your issue occurs with:

- CLI: 5.2.0
- Cross-platform modules: 5.0.5
- Runtime(s): 5.0.0
- Plugin(s):
```json
"dependencies": {
    "@vue/devtools": "~5.0.0-beta.3",
    "babel-eslint": "^8.2.3",
    "import-glob": "^1.5.0",
    "lodash": "^4.17.11",
    "nativescript-bottom-navigation": "~1.4.4",
    "nativescript-cardview": "~3.1.1",
    "nativescript-carousel": "~4.1.0",
    "nativescript-floatingactionbutton": "^5.0.0",
    "nativescript-localize": "~4.1.0",
    "nativescript-pager": "^9.3.14",
    "nativescript-secure-storage": "^2.4.0",
    "nativescript-socket.io": "~0.9.0",
    "nativescript-toast": "~1.4.6",
    "nativescript-ui-chart": "^3.11.1",
    "nativescript-vue": "~2.0.0",
    "nativescript-vue-devtools": "~1.1.0",
    "tns-core-modules": "~5.0.2",
    "vuex": "~3.0.1"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0",
    "@babel/preset-env": "^7.0.0",
    "babel-loader": "^8.0.2",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "clean-webpack-plugin": "^0.1.19",
    "copy-webpack-plugin": "^4.5.2",
    "css-loader": "^1.0.0",
    "eslint": "^5.14.1",
    "eslint-config-airbnb-base": "^13.1.0",
    "eslint-config-standard": "^11.0.0",
    "eslint-plugin-import": "^2.16.0",
    "eslint-plugin-json": "^1.4.0",
    "eslint-plugin-node": "^6.0.1",
    "eslint-plugin-promise": "^3.8.0",
    "eslint-plugin-standard": "^3.1.0",
    "eslint-plugin-vue": "^5.2.2",
    "lazy": "1.0.11",
    "nativescript-dev-webpack": "next",
    "nativescript-vue-template-compiler": "^2.0.0",
    "nativescript-worker-loader": "~0.9.0",
    "node-sass": "^4.9.2",
    "sass-loader": "^7.1.0",
    "sass-resources-loader": "^2.0.0",
    "terser-webpack-plugin": "^1.1.0",
    "vue-loader": "~15.2.6",
    "webpack": "^4.16.4",
    "webpack-bundle-analyzer": "~2.13.1",
    "webpack-cli": "^3.1.0"
  }
```

### Please, tell us how to recreate the issue in as much detail as possible. 
I've created a pager in my nativescript-vue application dynamically (via "for"-attribute) with a default data items array, accordingly to the example provided.

In my mounted method, after a few seconds of waiting, i add further items to the data array.

Now the slider still works as expected, problem is though, if i try to scroll to the newly added item the app just crashes silently, no output in the logs. So in this example i see: 
* "prev" -> ok
* scroll once -> "prev1" -> ok
* scroll once -> "prev2" -> ok
* scroll once -> nothing there -> app crashes

(this case is a simplified example, originally i have a vuex store as the items storage. for the sake of this example it has been removed as it's also easier to reproduce)

Is this a bug or am I just simply using the component wrong?

### Is there any code involved?
default import of the components in index.js:
```javascript
import Vue from 'nativescript-vue'
import Pager from 'nativescript-pager/vue'

Vue.use(Pager)
/* + many more libraries */
```

VueJS single file component

```javascript

<template>
    <Page>
        <GridLayout rows="auto, *">
            <Pager
                    row="1"
                    for="item in items"
                    height="80%"
            >
                <v-template>
                    <Label :text="item.number"/>
                </v-template>
            </Pager>
        </GridLayout>
    </Page>
</template>
<script>
    export default {
        data () {
            return {
                items: ([{
                    number: 'prev',
                    moreitems: []
                }, {
                    number: 'prev1',
                    moreitems: []
                }, {
                    number: 'prev2',
                    moreitems: []
                }])
            }
        },
        mounted () {
            let nr = 0
            let int = setInterval(() => {
                console.log('pushed ' + nr)
                this.items.push({
                    number: 'new' + nr,
                    moreitems: []
                })
                console.log(this.items)
                nr++
                if (nr > 2) {
                    clearInterval(int)
                }
            }, 2000)
        }
    }
</script>
<style lang="scss" scoped>
</style>
```

**Comment by triniwiz** [comment]
Where is ‘this.territories.push’ used also if you check in the demos you will see examples of infinite scrolling

**Comment by tweichart** [comment]
sorry for that, updated the example. of course it's `this.items.push` ;-)

the only example i could find is this: https://github.com/triniwiz/nativescript-pager/blob/master/demo-vue/app/components/App.vue

there the items are set statically during initialisation, which also works for my example. the problem just appears when you start to add items to the `this.items` data **during runtime** , the newly added items can't be displayed for whatever reason.

sidenote, this is propaply a bug only related to the vue implementation.

**Comment by triniwiz** [comment]
Can u add `cache=“false”` to the pager element and LMK what happens 🙂

**Comment by tweichart** [comment]
so i simply changed added `cache="false"` to the Pager component and it works like a charm now, adding new items works and they are displayed correctly 🎉 👍 

seems like it's only breaking when cache is true, but i can work with that for now. should i leave the issue open until there's a fix? thanks a lot though!

**Comment by triniwiz** [comment]
You could leave it open because a simple push should work out but using slice needs that attribute 🤔 on android it’s not needed though
