### ISSUE TITLE
Rendering issues on android when navigating

### ISSUE THREAD

**Issue by nilshohmann** [triniwiz/nativescript-pager#99]
Hey, I'm pretty new to nativescript and I've tried to use the nativescript-pager in one of my apps. I'm currently facing an issues on android with the latest version. I'm using `angular` and have the following navigation structure:

- app (containing a side drawer)
  - home
     - overview (containing the pager)
     - other page
  - details

On the `/home/overview` page five items are shown within a nativescript-pager using an angular template for rendering. When selecting an item the `/details` page is opened via RouterExtensions. When navigating back to `/home/overview` page and swiping through the pager, the items on the first and last index are not rendered anymore. The general behavior indicates a recycling issues on the underlying android `PagerView`.

When navigating to another page within `/home` and back to `/home/overview` the pager works as expected again.

I couldn't reproduce the error on the emulator but only on physical devices. It happens with version 9.3.7 and after, before that it seems to work properly.

### Versions

- NativeScript: 5.2.0
- Angular: 7.2.7
- Plugin: nativescript-pager @ 9.3.15
- Devices:
  - Moto Z Play (Android 8.0.0)
  - Samsung Galaxy Tab A (Android 8.1.0)

### Sample repo

I created a sample project from the default angular / SideDrawer template:

https://github.com/nilshohmann/NativeScriptPagerIssue

To reproduce the error just tap on any of the items in the pager to open the details page. Then navigate back and swipe through the pager items. The items at index 0 and 4 are now missing. When navigating to the settings page (via the side drawer) and back to the items page all items are rendered again.

**Comment by sifex** [comment]
@triniwiz Still an issue

**Comment by triniwiz** [comment]
@sifex what type of array are you using ?

**Comment by sifex** [comment]
@triniwiz No array, static templating on NS Vue
